Documentation for new parameters in logstash-output-opensearch 2.0.0
opensearch-project/documentation-website pull request #1263
Opened 2022-09-19 16:03 UTC by deepdatta

Add documentation for 3 new parameters added in logstash-output-opensearch 2.0.0

Signed-off-by: Deep Datta <deedatta@amazon.com>

### Description
Add documentation for 3 new parameters added in logstash-output-opensearch 2.0.0
https://github.com/opensearch-project/logstash-output-opensearch/releases/tag/2.0.0

### Issues Resolved
https://github.com/opensearch-project/logstash-output-opensearch/pull/174

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-19 19:04 UTC, Naarcha-AWS approved these changes

2022-09-19 19:04 UTC, Naarcha-AWS commented on _clients/logstash/ship-to-opensearch.md
> +- service_name (string, default => "es") - defines the service name to be used for `aws_iam` authentication.
```suggestion
- service_name (string, default => "es") - Defines the service name to be used for `aws_iam` authentication.
```

2022-09-19 19:04 UTC, Naarcha-AWS commented on _clients/logstash/ship-to-opensearch.md
>  - template_name (string, default => "logstash") - defines how the template is named inside Opensearch
```suggestion
- template_name (string, default => "logstash") - Defines how the template is named inside Opensearch
```

2022-09-19 19:06 UTC, Naarcha-AWS requested changes

2022-09-19 19:06 UTC, Naarcha-AWS commented on _clients/logstash/ship-to-opensearch.md
>  - template (path) - You can set the path to your own template here, if you so desire. If not set, the included template will be used.
Remove "if you so desire".
```suggestion
- template (path) - You can set the path to your own template here. If not template is specified, the included template will be used.
```

2022-09-21 00:26 UTC, Naarcha-AWS requested changes

2022-09-21 00:26 UTC, Naarcha-AWS commented on _clients/logstash/ship-to-opensearch.md
> +- template (path) - You can set the path to your own template here. If not template is specified, the included template will be used.
```suggestion
- template (path) - You can set the path to your own template here. If no template is specified, Logstash uses the default template.
```

2022-09-21 00:32 UTC, Naarcha-AWS commented
@deepdatta: Your PR require DCO sign-off before we can merge. For instructions on how to amend your commits, try an [interactive rebase](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md#fix-option-3-interactive-rebase).

2022-09-21 20:03 UTC, deepdatta commented
Made the change and added Signoff

2022-09-21 21:12 UTC, Naarcha-AWS requested changes
One last change here.

2022-09-21 21:12 UTC, Naarcha-AWS commented on _clients/logstash/ship-to-opensearch.md
> +- legacy_template (boolean, default => true) - Selects the OpenSearch template API. When `true`, uses legacy templates via the _template API. When `false`, uses composabe templates via the _index_tem
Fix spelling for "composable". 
```suggestion
- legacy_template (boolean, default => true) - Selects the OpenSearch template API. When `true`, uses legacy templates via the _template API. When `false`, uses composable templates via the _index_template API.
```

2022-09-22 17:14 UTC, Naarcha-AWS approved these changes

2022-09-26 18:19 UTC, lizsnyder approved these changes

2022-09-27 18:25 UTC, merged