Adds search backpressure documentation
opensearch-project/documentation-website pull request #1790
Opened 2022-11-02 15:17 UTC by kolchfa-aws

Fixes #795 

### Checklist
- [ x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-11-07 11:47 UTC, ketanv3 requested changes

2022-11-07 11:47 UTC, ketanv3 commented on _opensearch/search-backpressure.md
> +}
Sharing an up-to-date sample cancellation response. Can you please update?

```json
{
    "error": {
        "root_cause": [
            {
                "type": "task_cancelled_exception",
                "reason": "cancelled task with reason: cpu usage exceeded [17.9ms >= 15ms], elapsed time exceeded [1.1s >= 300ms]"
            },
            {
                "type": "task_cancelled_exception",
                "reason": "cancelled task with reason: elapsed time exceeded [1.1s >= 300ms]"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "foobar",
                "node": "7yIqOeMfRyWW1rHs2S4byw",
                "reason": {
                    "type": "task_cancelled_exception",
                    "reason": "cancelled task with reason: cpu usage exceeded [17.9ms >= 15ms], elapsed time exceeded [1.1s >= 300ms]"
                }
            },
            {
                "shard": 1,
                "index": "foobar",
                "node": "7yIqOeMfRyWW1rHs2S4byw",
                "reason": {
                    "type": "task_cancelled_exception",
                    "reason": "cancelled task with reason: elapsed time exceeded [1.1s >= 300ms]"
                }
            }
        ]
    },
    "status": 500
}
```

2022-11-07 12:12 UTC, ketanv3 requested changes

2022-11-07 12:12 UTC, ketanv3 commented on _opensearch/search-backpressure.md
> +An observer thread tracks the resource consumption of each task thread. It measures the resource consumption at several checkpoints during the query phase of a shard search request. If the node is de
I suggest re-wording this slightly.

> An observer thread periodically measures the resource usage of the node. If the node is determined to be under duress, then the resource usage of each search shard task is examined and compared against some tunable thresholds. CPU usage, heap usage and elapsed time are considered to give each task a cancellation score which is then used to cancel the most resource-intensive tasks.

2022-11-07 12:12 UTC, ketanv3 commented on _opensearch/search-backpressure.md
> +If a query is canceled, instead of receiving search results you receive an error from the server similar to the error below:
Depending on what all shards failed, it may be possible that OpenSearch returns partial results. Can we re-word this slightly?

2022-11-07 12:15 UTC, ketanv3 commented on _opensearch/search-backpressure.md
> +GET _nodes/stats/search_backpressure
nit: The response below is with human-readable fields enabled. Can you update this to:

```
GET _nodes/stats/search_backpressure?human=true
```

2022-11-07 12:21 UTC, ketanv3 commented on _opensearch/search-backpressure.md
> +rolling_avg_bytes | Integer | The rolling average heap usage for the 100 most recent tasks, in bytes.
nit: Rolling average is not hard-coded to work with just `100` most recent tasks.

This is a configurable setting defined by `search_backpressure.search_shard_task.heap_moving_average_window_size`. 100 is just the default value for it.

2022-11-07 12:51 UTC, ketanv3 commented on _opensearch/search-backpressure.md
> +search_backpressure.<br>&nbsp;&nbsp;&nbsp;&nbsp;search_task_elapsed_time_threshold | 30 seconds | The elapsed time threshold (in milliseconds) for one task before it is considered for cancellation.
Some of these settings have been renamed. Sharing the latest ones along with simplified descriptions.

* `search_backpressure.mode` (default monitor_only)
   The search backpressure [mode](#search-backpressure-modes). Valid values are `monitor_only`, `enforced`, or `disabled`.
   
* `search_backpressure.interval_millis` (default 1 second)
  The interval at which the observer thread measures the resource usage and cancels tasks.
  
* `search_backpressure.cancellation_ratio` (default 10%)
   The maximum number of tasks to cancel as a fraction of successful task completions.

* `search_backpressure.cancellation_rate` (default 0.003)
   The maximum number of tasks to cancel per millisecond of elapsed time.

* `search_backpressure.cancellation_burst` (default 10)
   The maximum number of tasks to cancel in a single iteration of the observer thread.

* `search_backpressure.node_duress.num_successive_breaches` (default 3)
   The number of of successive limit breaches after which the node is considered under duress.

* `search_backpressure.node_duress.cpu_threshold` (default 90%)
   The CPU usage threshold (in percentage) for a node to be considered in duress.

* `search_backpressure.node_duress.heap_threshold` (default 70%)
   The heap usage threshold (in percentage) for a node to be considered in duress.

* `search_backpressure.search_shard_task.total_heap_percent_threshold` (default 5%)
   The heap usage threshold (in percentage) for the sum of all search shard tasks before cancellation is applied.

* `search_backpressure.search_shard_task.heap_percent_threshold` (default 0.5%)
   The heap usage threshold (in percentage) for a single search shard task before it is considered for cancellation.

* `search_backpressure.search_shard_task.heap_variance` (default 2.0)
   The minimum variance of a single search shard task's heap usage usage compared to the rolling average of previously completed tasks before it is considered for cancellation.

* `search_backpressure.search_shard_task.heap_moving_average_window_size` (default 100)
   The number of previously completed search shard tasks to consider when calculating the moving average of heap usage.

* `search_backpressure.search_shard_task.cpu_time_millis_threshold` (default 15 seconds)
   The CPU usage threshold (in milliseconds) for a single search shard task before it is considered for cancellation.

* `search_backpressure.search_shard_task.elapsed_time_millis_threshold` (default 30 seconds)
   The elapsed time threshold (in milliseconds) for a single search shard task before it is considered for cancellation.

2022-11-07 14:04 UTC, ketanv3 commented
Thanks for these changes. LGTM!

2022-11-07 14:04 UTC, ketanv3 approved these changes

2022-11-07 17:54 UTC, nssuresh2007 approved these changes
Looks good to me!

2022-11-07 21:45 UTC, vagimeli approved these changes
Minimal changes. LGTM.

2022-11-07 21:45 UTC, vagimeli commented on _opensearch/search-backpressure.md
> +An observer thread periodically measures the resource usage of the node. If the node is determined to be under duress, OpenSearch examines the resource usage of each search shard task and compares it
Third sentence: insert comma after "heap usage."

2022-11-07 21:45 UTC, vagimeli commented on _opensearch/search-backpressure.md
> +If a query is canceled, OpenSearch may return partial results in case some shards failed. If all shards failed, OpenSearch returns an error from the server similar to the error below:
To clarify the second part of this sentence, I bolded my suggestion: "If a query is canceled, OpenSearch may return partial results **if some shards failed**."

2022-11-07 21:45 UTC, vagimeli commented on _opensearch/search-backpressure.md
> +search_backpressure.<br>&nbsp;&nbsp;&nbsp;&nbsp;search_shard_task.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;heap_variance | 2.0 | The minimum variance of a single search shard task's heap u
Delete second "usage" after "heap usage."

2022-11-07 21:45 UTC, vagimeli commented on _opensearch/search-backpressure.md
> +search_backpressure | Object | Contains statistics about search backpressure.
For consistency, either delete the verb "contains" in line 173 and 174 or add a verb to each description in lines 175-177.

2022-11-08 17:55 UTC, ariamarble approved these changes
LGTM

2022-11-08 19:04 UTC, natebower reviewed
@kolchfa-aws Please see my comments and changes and let me know if you have any questions. Thanks!

2022-11-09 21:15 UTC, kolchfa-aws commented on _opensearch/search-backpressure.md
> +An observer thread periodically measures the resource usage of the node. If the node is determined to be under duress, OpenSearch examines the resource usage of each search shard task and compares it
It's not "continues", it is whether it becomes under duress. So, we're checking periodically for the node health. Normally, it's not under duress. If we determine that it is under duress, then we remediate.

2022-11-10 14:35 UTC, kolchfa-aws commented on _opensearch/search-backpressure.md
> +OpenSearch limits the number of cancellations as a fraction of successful task completions and cancellations per unit time. It continues to monitor and cancel tasks until the node is no longer under
Reworded for clarity.

2022-11-10 16:17 UTC, merged