add heading for OpenSearch file system recommendation
opensearch-project/documentation-website pull request #3085
Opened 2023-02-27 11:31 UTC by rursprung

### Description
adding a heading allows creating a deep-link directly to this information, making it easier to direct others to it. the note itself doesn't actually belong to the OS recommendation as it has nothing to do with the OS it's running on.

### Issues Resolved
n/a (though it's a follow-up to #569 / #1644)

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-02-27 11:32 UTC, rursprung commented
this is just a suggestion, better wording is welcome (edits by maintainers is allowed, feel free to directly update things). it'd just be nice to be able to create a deep-link to it.

CC @JeffH-AWS who authored the original PR.

2023-02-27 17:55 UTC, Naarcha-AWS requested changes

2023-02-27 17:55 UTC, Naarcha-AWS commented on _install-and-configure/install-opensearch/index.md
>  {: .note}
If we go this route, I would suggest removing the note format.

```suggestion

```

2023-03-08 20:15 UTC, Naarcha-AWS approved these changes

2023-03-08 20:19 UTC, JeffH-AWS approved these changes
Thanks @rursprung!!

2023-03-08 20:20 UTC, JeffH-AWS commented
@Naarcha-AWS this needs backported to 1.3

2023-03-08 20:31 UTC, carolxob approved these changes
LGTM.

2023-03-08 21:23 UTC, merged