Fix 1.3 quickstart structure
opensearch-project/documentation-website pull request #3299
Opened 2023-03-08 18:13 UTC by vagimeli

### Description
Fix 1.3 quickstart structure to align with 2.x structure.

### Checklist
- [X] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-03-08 18:17 UTC, ariamarble approved these changes

2023-03-08 18:19 UTC, JeffH-AWS approved these changes

2023-03-08 18:20 UTC, Naarcha-AWS requested changes
Let's hold on merging this for now until the final TOC changes are backported.

2023-03-08 18:27 UTC, vagimeli commented
> 

this is just moving the file from a get-started folder so that the link path is the same as the 2.x quickstart pages, that is,  dashboards/quickstart-dashboards/ instead of dashboards/get-started/quickstart-dashboards/

2023-03-09 15:30 UTC, Naarcha-AWS commented
@vagimeli:  Since I'm the one who caused the merge conflict on your 1.3 rename of the Dashboards quickstart, I opened a new PR to fix it: https://github.com/opensearch-project/documentation-website/pull/3299

2023-03-09 15:30 UTC, closed without merging