Update update-by-query.md
opensearch-project/documentation-website pull request #3693
Opened 2023-04-05 21:43 UTC by seittema

Updated the slices parameter description to be in-line with what's actually available.  You can specify the string 'auto' as well.  The text is pulled from the [delete-by-query](https://github.com/opensearch-project/documentation-website/blob/main/_api-reference/document-apis/delete-by-query.md) documentation to keep in sync.

### Description
Update slices parameter definition

### Checklist
- [ X] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-04-06 16:44 UTC, Naarcha-AWS requested changes

2023-04-06 16:44 UTC, Naarcha-AWS commented on _api-reference/document-apis/update-by-query.md
> +slices | String or Integer | How many slices to cut the operation into for faster processing. Specify an integer to set how many slices to divide the operation into, or use `auto`, which tells OpenSe
```suggestion
slices | String or integer | The number slices to split an operation into for faster processing, specified by integer. When set to `auto` OpenSearch it should decides how many the number of slices for the operation. Default is `1`, which indicates an operation will not be split.
```

2023-04-06 16:55 UTC, Naarcha-AWS commented
Thanks for your contribution @seittema. I left a suggestion on how to fix.

2023-04-10 13:29 UTC, seittema commented
@Naarcha-AWS Should I update the [delete-by-query](https://github.com/opensearch-project/documentation-website/blob/main/_api-reference/document-apis/delete-by-query.md) to match your proposed changes?  The grammer in this PR was pulled from current release documentation so that it was consistent.

2023-04-10 19:02 UTC, Naarcha-AWS commented
@seittema: That would be super helpful! Thanks for calling that out.

2023-05-22 21:58 UTC, Naarcha-AWS approved these changes

2023-05-22 22:00 UTC, merged