Add S3 sink documentation
opensearch-project/documentation-website pull request #4340
Opened 2023-06-14 17:18 UTC by Naarcha-AWS

Fixes issue #4157 

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-07-05 19:48 UTC, dlvenable requested changes

2023-07-05 19:48 UTC, dlvenable commented on _data-prepper/pipelines/configuration/sinks/s3.md
> +`bucket` | Yes | String | The object from which to retrieve and store data. The `name` must match the name of your object store.
This is in the top-level configuration. That is, it is not under `aws:`.

2023-07-05 19:48 UTC, dlvenable commented on _data-prepper/pipelines/configuration/sinks/s3.md
> +`max_retries` | No | Integer | The maximum number of times a single request should retry when ingesting data to S3. Defaults to `5`.
This is in the top-level configuration. That is, it is not under `aws:`.

2023-07-05 19:48 UTC, dlvenable commented on _data-prepper/pipelines/configuration/sinks/s3.md
> +`object_key` | No | Sets the `path_prefix` and the `file_pattern` of the object store. Defaults to the S3 object `events-%{yyyy-MM-dd'T'hh-mm-ss}` found inside the root directory of the bucket.
This is in the top-level configuration. That is, it is not under `aws:`.

2023-07-05 19:48 UTC, dlvenable commented on _data-prepper/pipelines/configuration/sinks/s3.md
> +`maximum_size` | No | String | The maximum count or size of bytes that the S3 bucket can ingest. Defaults to `50mb`.
This value is required.

2023-07-05 19:48 UTC, dlvenable commented on _data-prepper/pipelines/configuration/sinks/s3.md
> +## buffer_type
Our general pattern in the documentation is to only create a sub-section in the documentation when there is a sub-section in the YAML.

This is going against that pattern. So this makes it seem like it follows underneath.

e.g.

```
buffer_type:
  local_file: ???
```

I recommend that you move this into a top-level configuration section.

2023-07-05 19:48 UTC, dlvenable commented on _data-prepper/pipelines/configuration/sinks/s3.md
> +
We are missing a top-level configuration section. We should add that, and it should indicate what options are available. I have a few other comments about other items that should get moved up there.

See the S3 source for the current pattern to use.

2023-07-05 19:58 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sinks/s3.md
> +## AWS configuration options
```suggestion
## Configuration 
```

2023-07-05 19:59 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sinks/s3.md
> +Use the following options when customizing the AWS section of the `s3` sink.
```suggestion
Use the following options when customizing the section of the `s3` sink.
```

2023-07-05 19:59 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sinks/s3.md
> +`maximum_size` | No | String | The maximum count or size of bytes that the S3 bucket can ingest. Defaults to `50mb`.
```suggestion
`maximum_size` | Yes | String | The maximum count or size of bytes that the S3 bucket can ingest. Defaults to `50mb`.
```

2023-07-18 18:14 UTC, cwillum approved these changes
LGTM

2023-07-18 18:14 UTC, cwillum commented on _data-prepper/pipelines/configuration/sinks/s3.md
> +`bucket` | Yes | String | The object from which to retrieve and store data. The `name` must match the name of your object store.
```suggestion
`bucket` | Yes | String | The object from which the data is retrieved and then stored. The `name` must match the name of your object store.
```

2023-07-18 18:14 UTC, cwillum commented on _data-prepper/pipelines/configuration/sinks/s3.md
> +`sts_role_arn` | No | String | The [AWS Security Token Service](https://docs.aws.amazon.com/STS/latest/APIReference/welcome.html) (AWS STS) role that the S3 sink assumes when sending request to S3. D
```suggestion
`sts_role_arn` | No | String | The [AWS Security Token Service](https://docs.aws.amazon.com/STS/latest/APIReference/welcome.html) (AWS STS) role that the S3 sink assumes when sending a request to S3. Defaults to the [standard SDK behavior for credentials](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials.html). 
```

2023-07-18 23:01 UTC, natebower reviewed
@Naarcha-AWS Please see my comments and changes and let me know if you have any questions. Thanks!

2023-07-18 23:06 UTC, merged

2023-07-25 17:51 UTC, dlvenable commented
Thanks @Naarcha-AWS for making the plugin documentation more consistent!