Add warning about plugin permission
opensearch-project/documentation-website pull request #4383
Opened 2023-06-22 01:13 UTC by peternied

### Description
I didn't see any documentation that described what an installed plugin can do - and it would be good to make sure cluster operators have expectations described somewhere.

### Issues Resolved
- Resolves #4382

### Checklist
- [X] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-06-22 01:14 UTC, peternied commented
@cwillum Would love your feedback on this change

2023-06-22 14:30 UTC, Naarcha-AWS requested changes

2023-06-22 14:30 UTC, Naarcha-AWS commented on _install-and-configure/plugins.md
> +## Considerations for Plugins
```suggestion

```

2023-06-22 14:30 UTC, Naarcha-AWS commented on _install-and-configure/plugins.md
> +In OpenSearch Plugins have the ability to access the data in the cluster, including metadata about cluster operations. Take care when selecting and installing plugins - only use those from trusted so
```suggestion
OpenSearch plugins give you the ability to access the data in the cluster, including metadata about cluster operations. To help mitigate risks to your cluster's data and integrity,  make sure that a custom plugin's source is reliable when selecting and installing custom OpenSearch plugins. Furthermore, make sure that you understand the function of a plugin before installing on an OpenSearch cluster.
```

2023-06-22 15:08 UTC, peternied commented
Thanks @Naarcha-AWS for the fast feedback and suggestions!

2023-06-30 17:52 UTC, peternied commented
@Naarcha-AWS I've updated the text based on @cwillum's suggestions, let me know what you think

2023-07-05 18:12 UTC, Naarcha-AWS approved these changes

2023-07-05 18:12 UTC, merged