Update docs for Remote Segment and Remote Translog store stats surfaced via nodes/indices/cluster stats APIs
opensearch-project/documentation-website pull request #4995
Opened 2023-09-08 11:52 UTC by BhumikaSaini-Amazon

### Description
Update docs for Remote Segment and Remote Translog store stats surfaced via nodes/indices/cluster stats APIs

### Issues Resolved
* Resolves #4902
* Resolves #4903 
* Resolves #4993

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-09-12 17:15 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +segments.remote_store | Object | Statistics about Remote Segment Store operations.
```suggestion
segments.remote_store | Object | Statistics about remote segment store operations.
```

2023-09-12 17:15 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +segments.remote_store.upload | Object | Statistics about Remote Segment Store upload operations.
```suggestion
segments.remote_store.upload | Object | Statistics about remote segment store upload operations.
```

2023-09-12 17:41 UTC, Naarcha-AWS requested changes

2023-09-12 17:41 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +segments.remote_store.upload.total_upload_size.failed_bytes | Integer | The number of bytes for which upload to Remote Segment Store has failed.
```suggestion
segments.remote_store.upload.total_upload_size.failed_bytes | Integer | The number of bytes that failed to upload to the remote segment store.
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +segments.remote_store.upload.refresh_size_lag.max_bytes | Integer | The maximum bytes lag between the Remote Segment Store and local store.
```suggestion
segments.remote_store.upload.refresh_size_lag.max_bytes | Integer | The maximum lag in bytes during the upload refresh between the remote segment store and the local store.
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +segments.remote_store.download.total_download_size | Object | The amount of data downloaded from Remote Segment Store.
```suggestion
segments.remote_store.download.total_download_size | Object | The amount of data downloaded from the remote segment store.
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +segments.remote_store.download.total_download_size.started_bytes | Integer | The number of bytes for which download from Remote Segment Store has been started.
```suggestion
segments.remote_store.download.total_download_size.started_bytes | Integer | The number of bytes downloaded from the remote segment store after the download starts.
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +segments.remote_store.download.total_time_spent_in_millis | Integer | The total time duration (in milliseconds) spent on downloads from the Remote Segment Store.
```suggestion
segments.remote_store.download.total_time_spent_in_millis | Integer | The total duration in milliseconds spent on downloads from the remote segment store.
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +translog.remote_store | Object | Statistics about Remote Translog Store operations.
```suggestion
translog.remote_store | Object | Statistics related to operations from the remote translog store.
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +translog.remote_store.upload.total_uploads | Object | The number of syncs to Remote Translog Store.
```suggestion
translog.remote_store.upload.total_uploads | Object | The number of syncs to the remote translog store.
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +translog.remote_store.upload.total_uploads.started | Integer | The number of syncs to Remote Translog Store that have been started.
```suggestion
translog.remote_store.upload.total_uploads.started | Integer | The number of upload syncs to the remote translog store that have started.
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +translog.remote_store.upload.total_uploads.failed | Integer | The number of syncs to Remote Translog Store that have failed.
```suggestion
translog.remote_store.upload.total_uploads.failed | Integer | The number of failed upload syncs to the remote translog store.
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +translog.remote_store.upload.total_uploads.succeeded | Integer | The number of syncs to Remote Translog Store that have succeeded.
```suggestion
translog.remote_store.upload.total_uploads.succeeded | Integer | The number of successful upload syncs to the remote translog store.
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +translog.remote_store.upload.total_upload_size | Object | The amount of data uploaded to Remote Translog Store.
```suggestion
translog.remote_store.upload.total_upload_size | Object | The amount of data uploaded to the remote translog store.
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +translog.remote_store.upload.total_upload_size.started_bytes | Integer | The number of bytes for which upload to Remote Translog Store has been started.
```suggestion
translog.remote_store.upload.total_upload_size.started_bytes | Integer | The number of bytes actively uploading to the remote translog store after the upload has started.
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +translog.remote_store.upload.total_upload_size.failed_bytes | Integer | The number of bytes for which upload to Remote Translog Store has failed.
```suggestion
translog.remote_store.upload.total_upload_size.failed_bytes | Integer | The number of bytes that failed to upload to the remote translog store.
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +translog.remote_store.upload.total_upload_size.succeeded_bytes | Integer | The number of bytes for which upload to Remote Translog Store has succeeded.
```suggestion
translog.remote_store.upload.total_upload_size.succeeded_bytes | Integer | The number of bytes successfully uploaded to the remote translog store.
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _tuning-your-cluster/availability-and-recovery/remote-store/remote-segment-backpressure.md
> +- **Bytes lag**:  The bytes lag is computed by adding the size of all files that are present in local committed segments but not in the remote store. The backpressure is activated if the bytes lag is
```suggestion
- **Bytes lag**:  The bytes lag is computed by adding the size of all files that are present in local committed segments but not in the remote store. Backpressure is activated if the bytes lag is greater than _K_ multiplied by the moving average of the size in, in bytes, of files uploaded after each refresh. The variance factor _K_ is configurable in `remote_store.segment.pressure.bytes_lag.variance_factor`. The moving window size is configurable through the `remote_store.moving_average_window_size` setting.
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _tuning-your-cluster/availability-and-recovery/remote-store/remote-segment-backpressure.md
> +- **Time lag**: The time lag is computed by comparing the timestamps of the most recent local refresh and the most recent remote store segment upload. The backpressure is activated if the time lag is
```suggestion
- **Time lag**: The time lag is computed by comparing the timestamps of the most recent local refresh and the most recent remote store segment upload. Backpressure is activated if the time lag is greater than _K_ multiplied by the moving average of the time taken to upload new segments and metadata file after each refresh. The variance factor _K_ is configurable through `remote_store.segment.pressure.time_lag.variance_factor` setting. The moving window size is configurable through the `remote_store.moving_average_window_size` setting.  
```

2023-09-12 17:41 UTC, Naarcha-AWS commented on _tuning-your-cluster/availability-and-recovery/remote-store/remote-segment-backpressure.md
> +|`remote_store.moving_average_window_size`	|Integer | The moving average window size used to calculate the rolling statistic values exposed through [Remote Store Stats API]({{site.url}}{{site.baseurl
```suggestion
| `remote_store.moving_average_window_size` | Integer | The moving average window size used to calculate the rolling statistic values exposed through [Remote Store Stats API]({{site.url}}{{site.baseurl}}/tuning-your-cluster/availability-and-recovery/remote-store/remote-store-stats-api/). Default is `20`. Minimum enforced is `5`. |
```

2023-09-13 16:08 UTC, Naarcha-AWS approved these changes

2023-09-13 17:05 UTC, natebower reviewed
@Naarcha-AWS Please see my comments and changes and let me know if you have any questions. Thanks!

2023-09-13 17:05 UTC, natebower commented on _tuning-your-cluster/availability-and-recovery/remote-store/remote-segment-backpressure.md
> +- **Bytes lag**:  The bytes lag is computed by adding the size of all files that are present in local committed segments but not in the remote store. Backpressure is activated if the bytes lag is gre
```suggestion
- **Bytes lag**: The bytes lag is calculated by adding the sizes of all the files that are present in local committed segments but not in the remote store. Backpressure is activated if the bytes lag is greater than _K_ multiplied by the moving average of the size, in bytes, of the files uploaded after each refresh. The variance factor _K_ is configurable in `remote_store.segment.pressure.bytes_lag.variance_factor`. The moving window size is configurable through the `remote_store.moving_average_window_size` setting.
```

2023-09-13 17:05 UTC, natebower commented on _tuning-your-cluster/availability-and-recovery/remote-store/remote-segment-backpressure.md
> +- **Time lag**: The time lag is computed by comparing the timestamps of the most recent local refresh and the most recent remote store segment upload. Backpressure is activated if the time lag is gre
```suggestion
- **Time lag**: The time lag is calculated by comparing the timestamps of the most recent local refresh and the most recent remote store segment upload. Backpressure is activated if the time lag is greater than _K_ multiplied by the moving average of the time taken to upload new segments and metadata files after each refresh. The variance factor _K_ is configurable through the `remote_store.segment.pressure.time_lag.variance_factor` setting. The moving window size is configurable through the `remote_store.moving_average_window_size` setting.  
```

2023-09-13 17:05 UTC, natebower commented on _tuning-your-cluster/availability-and-recovery/remote-store/remote-segment-backpressure.md
> +| `remote_store.moving_average_window_size` | Integer | The moving average window size used to calculate the rolling statistic values exposed through [Remote Store Stats API]({{site.url}}{{site.baseu
```suggestion
| `remote_store.moving_average_window_size` | Integer | The moving average window size used to calculate the rolling statistic values exposed through the [Remote Store Stats API]({{site.url}}{{site.baseurl}}/tuning-your-cluster/availability-and-recovery/remote-store/remote-store-stats-api/). Default is `20`. Minimum enforced is `5`. |
```

2023-09-13 17:47 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +segments.remote_store.download.total_download_size | Object | The amount of data downloaded from the remote segment store.
```suggestion
segments.remote_store.download.total_download_size | Object | The total amount of data download from the remote segment store.
```

2023-09-13 17:47 UTC, Naarcha-AWS commented on _api-reference/nodes-apis/nodes-stats.md
> +translog.remote_store.upload.total_upload_size | Object | The amount of data uploaded to the remote translog store.
```suggestion
translog.remote_store.upload.total_upload_size | Object | The total amount of data uploaded to the remote translog store.
```

2023-09-13 17:54 UTC, merged