Add a note about zstd incompatibility with k-NN and security analytics
opensearch-project/documentation-website pull request #5014
Opened 2023-09-13 18:41 UTC by kolchfa-aws

Fixes #5002 

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-09-13 18:41 UTC, kolchfa-aws commented
@sarthakaggarwal97 Could you review this PR please?

2023-09-14 01:32 UTC, sarthakaggarwal97 commented
LGTM! thanks @kolchfa-aws for taking this up!

2023-09-14 01:42 UTC, sarthakaggarwal97 commented on _im-plugin/index-codecs.md
> +As of OpenSearch 2.10, the `zstd` and `zstd_no_dict` codecs are not compatible with the [k-NN]({{site.url}}{{site.baseurl}}/search-plugins/knn/index/) and [Security Analytics]({{site.url}}{{site.base
Can we rephrase it to 


> As of OpenSearch 2.10, the `zstd` and `zstd_no_dict` codecs are not compatible with the [k-NN]({{site.url}}{{site.baseurl}}/search-plugins/knn/index/) and [Security Analytics]({{site.url}}{{site.baseurl}}/security-analytics/index/) indices.

2023-09-14 01:44 UTC, sarthakaggarwal97 requested changes
Minor comment, zstd and zstd_no_dict codecs will not be usable for the knn/ security-analytics indices. They can still be installed together

2023-09-14 01:53 UTC, kolchfa-aws commented on _im-plugin/index-codecs.md
> +As of OpenSearch 2.10, the `zstd` and `zstd_no_dict` codecs are not compatible with the [k-NN]({{site.url}}{{site.baseurl}}/search-plugins/knn/index/) and [Security Analytics]({{site.url}}{{site.base
```suggestion
As of OpenSearch 2.10, the `zstd` and `zstd_no_dict` compression codecs cannot be used for [k-NN]({{site.url}}{{site.baseurl}}/search-plugins/knn/index/) and [Security Analytics]({{site.url}}{{site.baseurl}}/security-analytics/index/) indexes.
```

2023-09-14 02:04 UTC, sarthakaggarwal97 approved these changes
thanks @kolchfa-aws , looks good!

2023-09-14 12:11 UTC, natebower commented on _im-plugin/index-codecs.md
> +As of OpenSearch 2.10, the `zstd` and `zstd_no_dict` compression codecs cannot be used for [k-NN]({{site.url}}{{site.baseurl}}/search-plugins/knn/index/) and [Security Analytics]({{site.url}}{{site.b
```suggestion
As of OpenSearch 2.10, the `zstd` and `zstd_no_dict` compression codecs cannot be used for [k-NN]({{site.url}}{{site.baseurl}}/search-plugins/knn/index/) or [Security Analytics]({{site.url}}{{site.baseurl}}/security-analytics/index/) indexes.
```

2023-09-14 12:11 UTC, natebower approved these changes
LGTM with one minor change.

2023-09-22 21:30 UTC, merged