Documentation for the Data Prepper OpenSearch source
opensearch-project/documentation-website pull request #5144
Opened 2023-10-03 21:18 UTC by graytaylor0

### Description
Adds documentation for the OpenSearch source of Data Prepper that will be released in Data Prepper 2.5

### Issues Resolved
Resolves #5112 

### Checklist
- [ ] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-10-09 16:28 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +title: opensearch source
```suggestion
title: opensearch 
```

2023-10-11 15:36 UTC, Naarcha-AWS approved these changes
I committed my edits directly on top of this PR. Should now be ready for editorial review.

2023-10-11 16:28 UTC, natebower requested changes
@Naarcha-AWS Requesting changes so I can verify a few lines. Please tag me when complete. Thanks!

2023-10-11 16:28 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +`indices` | No | Object | The indices configuration for filtering which indexes are processed. Defaults to all indices, including system indices. For more information, see [Indices](#indices).
```suggestion
`indices` | No | Object | The configuration for filtering which indexes are processed. Defaults to all indexes, including system indexes. For more information, see [Indices](#indices).
```

2023-10-11 16:28 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +Use the following setting under the `include` and `exclude` options to indicate the regex pattern for the index.
Add a row between the intro and the table.

2023-10-11 16:28 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +`batch_size` | No       | Integer | The number of documents to read at a time while paginating from OpenSearch. Default is `1000`
```suggestion
`batch_size` | No       | Integer | The number of documents to read while paginating from OpenSearch. Default is `1000`. 
```

2023-10-11 16:28 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +`search_context_type` | No | Enum | An override for the type of search/pagination to use on indices. Can be [point_in_time]({{site.url}}{{site.baseurl}}/search-plugins/searching-data/paginate/#point-
```suggestion
`search_context_type` | No | Enum | An override for the type of search/pagination to use on indexes. Can be [point_in_time]({{site.url}}{{site.baseurl}}/search-plugins/searching-data/paginate/#point-in-time-with-search_after)), [scroll]({{site.url}}{{site.baseurl}}/search-plugins/searching-data/paginate/#scroll-search), or `none`. The `none` option will use the [search_after]({{site.url}}{{site.baseurl}}/search-plugins/searching-data/paginate/#the-search_after-parameter) parameter. For more information, see [Default Search Behavior](#default_search_behavior).
```

2023-10-11 16:28 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +By default, the `opensearch` source will lookip the cluster version and distribution to determine
```suggestion
By default, the `opensearch` source will look up the cluster version and distribution to determine 
```

2023-10-11 16:28 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +will be used because neither `point_in_time` or `scroll` are supported by collections.
```suggestion
will be used because neither `point_in_time` nor `scroll` are supported by collections.
```

2023-10-11 16:28 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +`cert` | No | String  | The path to the security certificate, for example `"config/root-ca.pem"`, when the cluster uses the OpenSearch Security plugin.
```suggestion
`cert` | No | String  | The path to the security certificate, for example, `"config/root-ca.pem"`, when the cluster uses the OpenSearch Security plugin.
```

2023-10-11 16:28 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +`serverless` | No | Boolean | Should be set to true when processing from an Amazon OpenSearch Serverless collection. Defaults to false.
```suggestion
`serverless` | No | Boolean | Should be set to `true` when processing from an Amazon OpenSearch Serverless collection. Defaults to `false`.
```

2023-10-11 16:28 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +In order to pull data from an OpenSearch cluster using the `opensearch` source plugin, you must specify your username and password within the pipeline configuration. The following example `pipelines.
Should `pipelines.yaml` be `pipeline.yaml`?

2023-10-11 16:28 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +The `opensearch` source plugin can pull data from an [Amazon OpenSearch Service](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/what-is.html) domain, which uses IAM for security
```suggestion
The `opensearch` source plugin can pull data from an [Amazon OpenSearch Service](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/what-is.html) domain, which uses AWS Identity and Access Management (IAM) for security. The plugin uses the default Amazon OpenSearch Service credential chain. Run `aws configure` using the [AWS Command Line Interface (AWS CLI)](https://aws.amazon.com/cli/) to set your credentials.
```

2023-10-11 16:28 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +You can not read from a collection that uses virtual private cloud (VPC) access. The collection must be accessible from public networks.
```suggestion
You cannot read from a collection that uses virtual private cloud (VPC) access. The collection must be accessible from public networks.
```

2023-10-11 16:28 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +Make sure to replace the ARN in the `Principal` element with the ARN of the pipeline role that you created in the preceding step.
```suggestion
Make sure to replace the Amazon Resource Name (ARN) in the `Principal` element with the ARN of the pipeline role that you created in the preceding step.
```

2023-10-11 16:28 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> + For instructions on how to create collections, see [Creating collections](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-manage.html#serverless-create) in the Amazon
```suggestion
For instructions on how to create collections, see [Creating collections](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-manage.html#serverless-create) in the Amazon OpenSearch Service documentation.
```

2023-10-11 16:28 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +Within your `pipelines.yaml` file, specify the OpenSearch Serverless collection endpoint as the `hosts` option. In addition, you must set the `serverless` option to `true`. Specify the pipeline role
Should `pipelines.yaml` be `pipeline.yaml`?

2023-10-11 16:44 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +`search_options` | No | Object | The search options configuration. For more information, see [Search options](#search_options).
```suggestion
`search_options` | No | Object | A list of search options of procedures. For more information, see [Search options](#search_options).
```

2023-10-11 16:46 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +Option | Required | Type            | Description
Let me know if the edit shown above works for you.

2023-10-11 16:51 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +`interval` | No | String | The interval to reprocess indexes. Supports ISO_8601 notation Strings ("PT20.345S", "PT15M", etc.) as well as simple notation Strings for seconds ("60s") and milliseconds (
```suggestion
`interval` | No | String | The interval in which indexes are reprocessed. Supports ISO_8601 notation strings, such as "PT20.345S" or "PT15M", as well as simple notation strings for seconds ("60s") and milliseconds ("1500ms"). Defaults to `8h`.
```

2023-10-11 16:55 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +The following options help the `opensearch` source which indexes are processed from the source cluster using regex patterns. An index will only be processed if it matches one of the `index_name_regex
```suggestion
The following options help the `opensearch` source determine which indexes are processed from the source cluster using regex patterns. An index will only be processed if it matches one of the `index_name_regex` patterns under the `include` setting and does not match any of the 
```

2023-10-11 17:15 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +Use the following setting under the `include` and `exclude` options to indicate the regex pattern for the index.
```suggestion

Use the following setting under the `include` and `exclude` options to indicate the regex pattern for the index.
```

2023-10-11 17:16 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +In order to pull data from an OpenSearch cluster using the `opensearch` source plugin, you must specify your username and password within the pipeline configuration. The following example `pipelines.
```suggestion
In order to pull data from an OpenSearch cluster using the `opensearch` source plugin, you must specify your username and password within the pipeline configuration. The following example `pipeline.yaml` file demonstrates how to specify the default admin security credentials:
```

2023-10-11 17:16 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +Within your `pipelines.yaml` file, specify the OpenSearch Serverless collection endpoint as the `hosts` option. In addition, you must set the `serverless` option to `true`. Specify the pipeline role
```suggestion
Within your `pipeline.yaml` file, specify the OpenSearch Serverless collection endpoint as the `hosts` option. In addition, you must set the `serverless` option to `true`. Specify the pipeline role in the `sts_role_arn` option, as shown in the following example:
```

2023-10-11 17:38 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +When the `opensource` source constructs Data Prepper events from documents in the cluster, the document index is stored in the EventMetadata with an `opensearch-index` key, and the document_id is sto
```suggestion
When the `opensource` source constructs Data Prepper events from documents in the cluster, the document index is stored in the EventMetadata with an `opensearch-index` key, and the document_id is stored in the `EventMetadata` with the `opensearch-document_id` as the key. This allows for conditional routing based on the index or `document_id`. The following example pipeline configuration sends events to an `opensearch` sink and uses the same index and `document_id` from the source cluster as in the destination cluster:
```

2023-10-11 17:39 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +`start_time` | No | String | The instant of time when processing should begin. The source will not start processing until this instant is reached. The String must be in ISO-8601 format, such as `2007
```suggestion
`start_time` | No | String | The time when processing should begin. The source will not start processing until this instant is reached. The String must be in ISO-8601 format, such as `2007-12-03T10:15:30.00Z`. The default option starts processing immediately. 
```

2023-10-11 17:39 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +`include` | No | Array of Objects | A list of index configuration patterns that specifies which indexes will be processed.
```suggestion
`include` | No | Array of objects | A list of index configuration patterns that specifies which indexes will be processed.
```

2023-10-11 17:39 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +`index_name_regex` | Yes | Regex String | The regex pattern to match indexes against.
```suggestion
`index_name_regex` | Yes | Regex string | The regex pattern to match indexes against. 
```

2023-10-11 17:40 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +In order to pull data from an OpenSearch cluster using the `opensearch` source plugin, you must specify your username and password within the pipeline configuration. The following example `pipelines.
```suggestion
In order to pull data from an OpenSearch cluster using the `opensearch` source plugin, you must specify your username and password within the pipeline configuration. The following example `pipelines.yaml` file demonstrates how to specify the default admin security credentials:
```

2023-10-11 17:51 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +For example, setting `index_read_count` to `3` with an `interval` of `1h` will result in all indexes being processed 3 times, 1 hour apart. By default, indexes will only be processed once.
```suggestion
For example, setting `index_read_count` to `3` with an `interval` of `1h` will result in all indexes being reprocessed 3 times, 1 hour apart. By default, indexes will only be processed once. 
```

2023-10-11 17:51 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +`start_time` | No | String | The time when processing should begin. The source will not start processing until this instant is reached. The String must be in ISO-8601 format, such as `2007-12-03T10:1
```suggestion
`start_time` | No | String | The time when processing should begin. The source will not start processing until this instant is reached. The string must be in ISO-8601 format, such as `2007-12-03T10:15:30.00Z`. The default option starts processing immediately. 
```

2023-10-11 17:53 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +`interval` | No | String | The interval in which indexes are reprocessed. Supports ISO_8601 notation strings, such as "PT20.345S" or "PT15M", as well as simple notation strings for seconds ("60s") an
```suggestion
`interval` | No | String | The interval that determines the amount of time between reprocessing. Supports ISO 8601 notation strings, such as "PT20.345S" or "PT15M", as well as simple notation strings for seconds ("60s") and milliseconds ("1500ms"). Defaults to `8h`.
```

2023-10-11 18:03 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +`start_time` | No | String | The time when processing should begin. The source will not start processing until this instant is reached. The string must be in ISO 8601 format, such as `2007-12-03T10:1
```suggestion
`start_time` | No | String | The time when processing should begin. The source will not start processing until this time. The string must be in ISO 8601 format, such as `2007-12-03T10:15:30.00Z`. The default option starts processing immediately. 
```

2023-10-11 18:06 UTC, natebower approved these changes
LGTM

2023-10-11 18:44 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +`search_context_type` | No | Enum | An override for the type of search/pagination to use on indexes. Can be [point_in_time]({{site.url}}{{site.baseurl}}/search-plugins/searching-data/paginate/#point-
```suggestion
`search_context_type` | No | Enum | An override for the type of search/pagination to use on indexes. Can be [point_in_time]({{site.url}}{{site.baseurl}}/search-plugins/searching-data/paginate/#point-in-time-with-search_after)), [scroll]({{site.url}}{{site.baseurl}}/search-plugins/searching-data/paginate/#scroll-search), or `none`. The `none` option will use the [search_after]({{site.url}}{{site.baseurl}}/search-plugins/searching-data/paginate/#the-search_after-parameter) parameter. For more information, see [Default Search Behavior](#default-search-behavior).
```

2023-10-11 18:48 UTC, merged