[DOC] Added Code Copying Functionality Across Repository Sections
opensearch-project/documentation-website pull request #5198
Opened 2023-10-13 12:59 UTC by KiranAminPanjwani

### Description
I've addressed various pages throughout the entire repository, including the API reference, Troubleshooting, Tools, and Data Prepper sections, to rectify inconsistencies in code snippet copying options. The following measures have been implemented:

- Verified that users can seamlessly copy commands, request bodies, examples, and request body formats.
- Implemented one-click copy functionality in previously missing areas to save users time and enhance their overall experience.

### Issues Resolved
Closes Issue #5183 

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-10-13 13:00 UTC, KiranAminPanjwani commented
@Naarcha-AWS Kindly review and merge my PR.😇

2023-10-16 14:12 UTC, Naarcha-AWS approved these changes
A quick clarifying question but otherwise LGTM.

2023-10-16 14:12 UTC, Naarcha-AWS commented on _api-reference/script-apis/exec-stored-script.md
> +````
Why are we adding an additional tick mark here and other places?

2023-10-16 20:13 UTC, kolchfa-aws commented
@KiranAminPanjwani: The rendering that you see happens not because it's 4 back tics instead of 3, but because the number of back tics opening the code block must be the same as the number of back tics closing the code block. On this page, some requests/responses have 4 opening back tics but only 3 closing ones, which makes Markdown confused :) 

4 back tics are necessary to escape a code block which itself contains 3 back tics (i.e., to display 3 back tics you need to escape them with 4 back tics). In all our requests and responses, 3 back tics is enough.

2023-10-17 14:59 UTC, KiranAminPanjwani commented
> > > @KiranAminPanjwani: The rendering that you see happens not because it's 4 back tics instead of 3, but because the number of back tics opening the code block must be the same as the number of back tics closing the code block. On this page, some requests/responses have 4 opening back tics but only 3 closing ones, which makes Markdown confused :)
> > > 4 back tics are necessary to escape a code block which itself contains 3 back tics (i.e., to display 3 back tics you need to escape them with 4 back tics). In all our requests and responses, 3 back tics is enough.
> > 
> > 
> > Acknowledged sir.✨ Should I edit the files again?
> 
> Yes.

Okay sir.

2023-10-18 19:22 UTC, KiranAminPanjwani commented
@Naarcha-AWS, @kolchfa-aws I have updated the file again. Kindly review and please let me know if any further modifications are needed.

2023-10-20 15:17 UTC, Naarcha-AWS commented
@KiranAminPanjwani: Should be good to merge once we fix the merge conflicts. Let me know if you need help with that.

2023-10-20 16:52 UTC, KiranAminPanjwani commented
> @KiranAminPanjwani: Should be good to merge once we fix the merge conflicts. Let me know if you need help with that.

Sir, I would greatly appreciate your assistance, as I'm having trouble identifying the specific conflicts.

![image](https://github.com/opensearch-project/documentation-website/assets/90326051/9ae2dead-41cd-458f-9506-b5969fb95af0)

2023-10-23 20:06 UTC, KiranAminPanjwani commented
> > @KiranAminPanjwani: Should be good to merge once we fix the merge conflicts. Let me know if you need help with that.
> 
> @Naarcha-AWS Sir, I would greatly appreciate your assistance, as I'm having trouble identifying the specific conflicts.
> 
> ![image](https://user-images.githubusercontent.com/90326051/276997660-9ae2dead-41cd-458f-9506-b5969fb95af0.png)

@Naarcha-AWS @kolchfa-aws Sir, Kindly guide me.✨

2023-10-24 15:00 UTC, Naarcha-AWS commented
@KiranAminPanjwani: This should help you get started: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line.

If you need someone to walk you through it, feel free to send me a message and I would be happy to assist.

2023-10-31 14:42 UTC, Naarcha-AWS commented
@KiranAminPanjwani: Do you still need help resolving these merge conflicts?

2023-10-31 19:35 UTC, KiranAminPanjwani commented
> @KiranAminPanjwani: Do you still need help resolving these merge conflicts?

Sir, I'm working on it.

2023-10-31 19:41 UTC, KiranAminPanjwani commented
> > @KiranAminPanjwani: Do you still need help resolving these merge conflicts?
> 
> Sir, I'm working on it.

@Naarcha-AWS Sir, I'm facing issues in resolving the conflicts at my end. Shall I create a new PR for this one?

2023-10-31 19:45 UTC, KiranAminPanjwani commented
> > > @KiranAminPanjwani: Do you still need help resolving these merge conflicts?
> > 
> > 
> > Sir, I'm working on it.
> 
> @Naarcha-AWS Sir, I'm facing issues in resolving the conflicts at my end. Shall I create a new PR for this one?
Could we please connect on Discord to discuss my issue?

2023-11-24 19:37 UTC, kolchfa-aws commented
@KiranAminPanjwani The "Path and HTTP methods" section does not need copy buttons. The purpose of this section is just to showcase the path and HTTP methods. For many requests, copying and running these would give an error because there is no payload for the request. Please remove copy buttons from these sections. Thanks!

2023-11-25 08:53 UTC, KiranAminPanjwani commented
> @KiranAminPanjwani The "Path and HTTP methods" section does not need copy buttons. The purpose of this section is just to showcase the path and HTTP methods. For many requests, copying and running these would give an error because there is no payload for the request. Please remove copy buttons from these sections. Thanks!

Okay, sir. Should I remove the copy button only from where the conflicts occur, or should I remove my addition from all the files?

2023-11-25 20:21 UTC, kolchfa-aws commented
Please remove the copy buttons from all "Path and HTTP methods" code snippets. Thank you!

2023-12-05 22:08 UTC, hdhalter commented
@KiranAminPanjwani , Hi Kiran, are you planning on finishing up this PR? Thanks!

2023-12-05 22:17 UTC, kolchfa-aws requested changes
Just so this doesn't get accidentally merged, let's make sure the Path and HTTP methods section does not have copy buttons. Thanks!

2023-12-06 10:11 UTC, KiranAminPanjwani commented
@Naarcha-AWS @hdhalter @kolchfa-aws 
Hi,
Yes, I'm working on it. I believe closing this pull request would be better, as it currently has conflicts. Therefore, I am closing this PR and will create a new one with the proper working.
Thank you.

2023-12-06 10:11 UTC, closed without merging