[DOC] Fix rename processor 'otel_trace' to 'otel_traces'
opensearch-project/documentation-website pull request #5423
Opened 2023-10-28 19:49 UTC by samipak458

### Description
Fix 'otel_trace_raw' processor [renamed](https://github.com/opensearch-project/data-prepper/tree/2.4.0/data-prepper-plugins/otel-trace-raw-processor) to 'otel_traces'. Simply add the missing "s" that causing an exception when using it.

### Issues Resolved
Fixes #4935

### Checklist
- [X] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-10-28 19:51 UTC, samipak458 commented
@Naarcha-AWS kindly review it.

2023-11-03 15:47 UTC, Naarcha-AWS commented on _data-prepper/common-use-cases/trace-analytics.md
> +* *otel_traces_raw* - The *otel_traces_raw* processor receives a collection of [span](https://github.com/opensearch-project/data-prepper/blob/fa65e9efb3f8d6a404a1ab1875f21ce85e5c5a6d/data-prepper-api
```suggestion
* *otel_traces_raw* - The *otel_traces_raw* processor receives a collection of [span](https://github.com/opensearch-project/data-prepper/blob/fa65e9efb3f8d6a404a1ab1875f21ce85e5c5a6d/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/trace/Span.java) records from [*otel_traces_source*]({{site.url}}{{site.baseurl}}/data-prepper/pipelines/configuration/sources/otel-trace/), and performs stateful processing, extraction, and completion of trace-group-related fields.
```

2023-11-03 16:24 UTC, Naarcha-AWS requested changes
A few small changes.

2023-11-03 16:24 UTC, Naarcha-AWS commented on _data-prepper/managing-data-prepper/peer-forwarder.md
> +Peer forwarder is an HTTP service that performs peer forwarding of an `event` between Data Prepper nodes for aggregation. This HTTP service uses a hash-ring approach to aggregate events and determine
```suggestion
Peer Forwarder is an HTTP service that performs peer forwarding of an `event` between Data Prepper nodes for aggregation. This HTTP service uses a hash-ring approach to aggregate events and determine which Data Prepper node it should handle on a given trace before rerouting it to that node. Currently, peer forwarder is supported by the `aggregate`, `service_map_stateful`, and `otel_traces_raw` [processors]({{site.url}}{{site.baseurl}}/data-prepper/pipelines/configuration/processors/processors/).
```

2023-11-03 16:24 UTC, Naarcha-AWS commented on _data-prepper/managing-data-prepper/peer-forwarder.md
>  # Peer forwarder
```suggestion
# Peer Forwarder
```

2023-11-03 16:24 UTC, Naarcha-AWS commented on _data-prepper/managing-data-prepper/peer-forwarder.md
> +Peer forwarder groups events based on the identification keys provided by the supported processors. For `service_map_stateful` and `otel_traces_raw`, the identification key is `traceId` by default an
```suggestion
Peer Forwarder groups events based on the identification keys provided by the supported processors. For `service_map_stateful` and `otel_traces_raw`, the identification key is `traceId` by default and cannot be configured. The `aggregate` processor is configured using the `identification_keys` configuration option. From here, you can specify which keys to use for peer forwarder. See the [Aggregate Processor page](https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/aggregate-processor#identification_keys) for more information about identification keys.
```

2023-11-03 20:10 UTC, samipak458 commented
All changes done as per requested. Kindly review it again @Naarcha-AWS

2023-11-06 17:41 UTC, Naarcha-AWS approved these changes
One last tweak but otherwise LGTM.

2023-11-06 17:41 UTC, Naarcha-AWS commented on _data-prepper/managing-data-prepper/peer-forwarder.md
> +Peer forwarder groups events based on the identification keys provided by the supported processors. For `service_map_stateful` and `otel_traces_raw`, the identification key is `traceId` by default an
```suggestion
Peer Forwarder groups events based on the identification keys provided by the supported processors. For `service_map_stateful` and `otel_traces_raw`, the identification key is `traceId` by default and cannot be configured. The `aggregate` processor is configured using the `identification_keys` configuration option. From here, you can specify which keys to use for Peer Forwarder. See [Aggregate Processor page](https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/aggregate-processor#identification_keys) for more information about identification keys.
```

2023-11-07 20:48 UTC, merged