Add distributed workload test tutoriall
opensearch-project/documentation-website pull request #5629
Opened 2023-11-17 18:57 UTC by Naarcha-AWS

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-11-17 20:36 UTC, IanHoang commented on _benchmark/user-guide/distributed-load.md
> +On **Node 1**, run a benchmark test with the `load-worker-coordinator-hosts` set to the IP addresses for your worker nodes, as shown in the following example:
`load-worker-coordinator-hosts` --> `worker-ips`

These have been updated in a recent PR. Sorry for the confusion!

2023-11-17 20:37 UTC, IanHoang commented on _benchmark/user-guide/distributed-load.md
> +opensearch-benchmarkd start —node-ip=192.0.1.0 —coordinator-ip=192.0.1.0
Need to ensure that the parameters use `--` for the beginning. For example, `—node-ip` should be `--node-ip` and `—coordinator-ip` should be `--coordinator-ip`.

2023-11-17 20:38 UTC, IanHoang commented on _benchmark/user-guide/distributed-load.md
> +opensearch-benchmark execute_test —pipeline=benchmark-only —workload=eventdata —load-worker-coordinator-hosts=198.52.100.0,198.53.100.0 —target-hosts=<DOMAIN_ENDPOINT> —client-options=<STANDARD_CLIEN
Can we revise this to ensure that the markdown shows `--` instead of a single line? Also `—load-worker-coordinator-hosts` --> `--worker-ips`

2023-11-17 21:07 UTC, IanHoang requested changes
Made some comments

2023-11-21 16:47 UTC, Naarcha-AWS commented on _benchmark/user-guide/distributed-load.md
> +By default, OpenSearch Benchmark runs loads on the same machine where the benchmark started. However, you can generate addiional benchmarking load, particularly on large clusters with multiple machin
```suggestion
By default, OpenSearch Benchmark runs loads on the same machine where the benchmark started. However, you can generate additional benchmarking testing loads, particularly on large clusters with multiple machines, you can use multiple load drivers. This page details how to distribute benchmark loads across multiple machines in a single cluster.
```

2023-11-21 16:48 UTC, Naarcha-AWS commented on _benchmark/user-guide/distributed-load.md
> +Now, start OpenSearch Benchmark on each node, using the `--node-ip` to intailize OpenSearch Benchmark on the node itself, then `--coordinator-ip` to connect each node to the Coordinator node.
```suggestion
Now, start OpenSearch Benchmark on each node, using the `--node-ip` to initialize OpenSearch Benchmark on the node itself, then `--coordinator-ip` to connect each node to the Coordinator node.
```

2023-11-21 16:48 UTC, Naarcha-AWS commented on _benchmark/user-guide/distributed-load.md
> +opensearch-benchmarkd start —node-ip=192.0.1.0 —coordinator-ip=192.0.1.0
```suggestion
opensearch-benchmarkd start --node-ip=192.0.1.0 --coordinator-ip=192.0.1.0
```

2023-11-21 16:49 UTC, Naarcha-AWS commented on _benchmark/user-guide/distributed-load.md
> +On **Node 1**, run a benchmark test with the `load-worker-coordinator-hosts` set to the IP addresses for your worker nodes, as shown in the following example:
```suggestion
On **Node 1**, run a benchmark test with the `worker-ips` set to the IP addresses for your worker nodes, as shown in the following example:
```

2023-11-21 16:49 UTC, Naarcha-AWS commented on _benchmark/user-guide/distributed-load.md
> +opensearch-benchmark execute_test —pipeline=benchmark-only —workload=eventdata —load-worker-coordinator-hosts=198.52.100.0,198.53.100.0 —target-hosts=<DOMAIN_ENDPOINT> —client-options=<STANDARD_CLIEN
```suggestion
opensearch-benchmark execute_test --pipeline=benchmark-only --workload=eventdata --worker-ips=198.52.100.0,198.53.100.0 --target-hosts=<DOMAIN_ENDPOINT> --client-options=<STANDARD_CLIENT_OPTIONS> --kill-running-processes
```

2023-11-21 17:26 UTC, IanHoang commented on _benchmark/user-guide/distributed-load.md
> +opensearch-benchmarkd start —node-ip=198.52.100.0 —coordinator-ip=192.0.1.0
`—node-ip` --> `--node-ip` 
`—coordinator-ip` --> `--coordinator-ip`

2023-11-21 17:26 UTC, IanHoang commented on _benchmark/user-guide/distributed-load.md
> +opensearch-benchmarkd start —node-ip=198.53.100.0 —coordinator-ip=192.0.1.0
`—node-ip` --> `--node-ip` 
`—coordinator-ip` --> `--coordinator-ip`

2023-11-21 17:27 UTC, IanHoang approved these changes
Left two comments to fix and it's good

2023-11-21 18:22 UTC, Naarcha-AWS commented on _benchmark/user-guide/distributed-load.md
> +opensearch-benchmarkd start —node-ip=198.52.100.0 —coordinator-ip=192.0.1.0
```suggestion
opensearch-benchmarkd start --node-ip=198.52.100.0 --coordinator-ip=192.0.1.0
```

2023-11-21 18:22 UTC, Naarcha-AWS commented on _benchmark/user-guide/distributed-load.md
> +opensearch-benchmarkd start —node-ip=198.53.100.0 —coordinator-ip=192.0.1.0
```suggestion
opensearch-benchmarkd start --node-ip=198.53.100.0 --coordinator-ip=192.0.1.0
```

2023-11-22 17:46 UTC, hdhalter reviewed
Hi Nate, I've added some suggestions to tighten up the text. Please make sure I did not change any meaning. Thanks!

2023-11-22 17:46 UTC, hdhalter commented on _benchmark/user-guide/distributed-load.md
> +For **Node 1**, the following command identifies the node as coordinator:
```suggestion
For **Node 1**, the following command identifies the node as coordinator:
```
_the_ coordinator?

2023-11-22 17:46 UTC, hdhalter commented on _benchmark/user-guide/distributed-load.md
> +## Step 3: Running the benchmark test
```suggestion
## Step 3: Run the benchmark test
```

2023-11-22 17:46 UTC, hdhalter commented on _benchmark/user-guide/distributed-load.md
> +With OpenSearch Benchmark running on all three nodes and the worker nodes set to listen to the coordinator node, you can now run the Benchmark test.
Move this statement below the heading, "Run the benchmark test"?

2023-12-01 19:38 UTC, Naarcha-AWS commented on _benchmark/user-guide/distributed-load.md
> +# Running distributed load generation
```suggestion
# Running distributed loads 
```

2023-12-01 19:39 UTC, Naarcha-AWS commented on _benchmark/user-guide/distributed-load.md
> +With OpenSearch Benchmark running on all three nodes and the worker nodes set to listen to the coordinator node, you can now run the Benchmark test.
```suggestion
With OpenSearch Benchmark running on all three nodes and the worker nodes set to listen to the coordinator node, you can now run the benchmark test.
```

2023-12-01 19:39 UTC, Naarcha-AWS commented on _benchmark/user-guide/distributed-load.md
> +
I'll ask Ian about this.

2023-12-01 19:39 UTC, Naarcha-AWS commented on _benchmark/user-guide/distributed-load.md
> +
I'll ask Ian about this.

2023-12-04 18:20 UTC, Naarcha-AWS commented on _benchmark/user-guide/distributed-load.md
> +title: Configuring OpenSearch Benchmark
```suggestion
title: Running distributed loads
```

2023-12-04 18:23 UTC, Naarcha-AWS commented on _benchmark/user-guide/distributed-load.md
> +After the test runs, the logs generated by the test appear on your worker nodes.
```suggestion
After the test completes, the logs generated by the test appear on your worker nodes.
```

2023-12-04 18:23 UTC, Naarcha-AWS commented on _benchmark/user-guide/distributed-load.md
> +
No troubleshooting steps at the moment. We'll add additional ones as we go along.

2023-12-04 19:12 UTC, natebower reviewed
@Naarcha-AWS Two minor changes and a comment. Tag me when complete. Thanks!

2023-12-04 19:12 UTC, natebower commented on _benchmark/user-guide/distributed-load.md
> +Start OpenSearch Benchmark on each node, using the `--node-ip` to initialize OpenSearch Benchmark on the node itself and then `--coordinator-ip` to connect each node to the coordinator node.
```suggestion
Start OpenSearch Benchmark on each node, using `--node-ip` to initialize OpenSearch Benchmark on the node itself and then `--coordinator-ip` to connect each node to the coordinator node.
```

2023-12-04 19:12 UTC, natebower commented on _benchmark/user-guide/distributed-load.md
> +The following commands enable **Node 2** and **Node 3** to listen to the coordinator node for load generation instructions:
```suggestion
The following commands enable **Node 2** and **Node 3** to listen to the coordinator node for load generation instructions.
```

2023-12-04 19:12 UTC, natebower commented on _benchmark/user-guide/distributed-load.md
> +**Node 1 -- Coordinator node**: 192.0.1.0
Should these be formatted as a bulleted list?

2023-12-04 19:18 UTC, natebower approved these changes
LGTM

2023-12-04 19:19 UTC, merged