Documentation for Data Prepper's kafka buffer
opensearch-project/documentation-website pull request #5689
Opened 2023-11-28 18:24 UTC by dlvenable

### Description

This adds a new page to the Data Prepper documentation for the new `kafka` buffer available in Data Prepper 2.6.0.

### Issues Resolved

N/A

### Checklist
- [ ] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-12-05 20:31 UTC, Naarcha-AWS commented
@dlvenable: Do you have a usage example for the `kafka` buffer?

2023-12-06 20:08 UTC, dlvenable commented
@Naarcha-AWS, I added an example pipeline configuration. Good suggestion.

2023-12-13 13:03 UTC, natebower requested changes
@Naarcha-AWS Please see my comments and changes and let me know if you have any questions. I'd like to read line 53 again before approving, so please tag me when complete. Thanks!

2023-12-13 13:03 UTC, natebower commented on _data-prepper/pipelines/configuration/buffers/kafka.md
> +#### AWS
Should this be "aws"?

2023-12-13 13:03 UTC, natebower commented on _data-prepper/pipelines/configuration/buffers/kafka.md
> +#### MSK
Should this be "msk"?

2023-12-13 13:03 UTC, natebower commented on _data-prepper/pipelines/configuration/buffers/kafka.md
> +`arn` | Yes | String | The [MSK ARN](https://docs.aws.amazon.com/msk/1.0/apireference/configurations-arn.html) to use.
```suggestion
`arn` | Yes | String | The [Amazon MSK ARN](https://docs.aws.amazon.com/msk/1.0/apireference/configurations-arn.html) to use.
```

2023-12-13 13:03 UTC, natebower commented on _data-prepper/pipelines/configuration/buffers/kafka.md
> +`broker_connection_type` No | String | The type of connector to use with the MSK broker, either `public`, `single_vpc`, or `multi_vpc`. Default is `single_vpc`.
```suggestion
`broker_connection_type` No | String | The type of connector to use with the Amazon MSK broker, either `public`, `single_vpc`, or `multi_vpc`. Default is `single_vpc`.
```

2023-12-13 19:01 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/buffers/kafka.md
> +Each `topic` configures a single Kafka topic and how to use that Kafka topic.
```suggestion
The `topic` option configures a single Kafka topic and tells the `kafka` buffer use that topic.
```

2023-12-13 19:01 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/buffers/kafka.md
> +Each `topic` configures a single Kafka topic and how to use that Kafka topic.
Does this work @natebower?

2023-12-13 19:02 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/buffers/kafka.md
> +`username` | String | The username for the PLAINTEXT auth.
```suggestion
`username` | String | The username for the PLAINTEXT authentication.
```

2023-12-13 19:02 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/buffers/kafka.md
> +`password` | String | The password for the PLAINTEXT auth.
```suggestion
`password` | String | The password for the PLAINTEXT authentication.
```

2023-12-13 19:02 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/buffers/kafka.md
> +#### AWS
```suggestion
#### aws
```

2023-12-13 19:03 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/buffers/kafka.md
> +#### MSK
```suggestion
#### msk
```

2023-12-13 19:13 UTC, natebower commented on _data-prepper/pipelines/configuration/buffers/kafka.md
> +Each `topic` configures a single Kafka topic and how to use that Kafka topic.
Yes, but "to" before "use".

2023-12-13 19:58 UTC, natebower approved these changes
LGTM

2023-12-13 20:12 UTC, merged