Document client certificate options to support mutual TLS for OpenID endpoint
opensearch-project/documentation-website pull request #5697
Opened 2023-11-29 06:33 UTC by Simple-Analysis

### Description
Users can configure options to enable mutual TLS when obtaining OpenID Connect endpoints from IdP.

### Issues Resolved
Relates to:
https://github.com/opensearch-project/security-dashboards-plugin/pull/1650

Fixes https://github.com/opensearch-project/documentation-website/issues/786

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-11-30 22:25 UTC, hdhalter commented
Thanks for submitting this PR, @Simple-Analysis ! And thanks for your review @cwperks. 

@Naarcha-AWS - can you please give it a doc review and get it merged? Looks like this fix addresses https://github.com/opensearch-project/documentation-website/issues/1499 and https://github.com/opensearch-project/documentation-website/issues/786.

2023-12-01 17:31 UTC, Naarcha-AWS requested changes

2023-12-01 17:31 UTC, Naarcha-AWS commented on _security/authentication-backends/openid-connect.md
> +`opensearch_security.openid.verify_hostnames` | Whether to verify the hostnames of the IdP's TLS certificate. Optional. Default is `true`.
```suggestion
`opensearch_security.openid.verify_hostnames` | Whether to verify the hostnames of the IdP's TLS certificate. Default is `true`. Optional. 
```

2023-12-01 17:31 UTC, Naarcha-AWS commented on _security/authentication-backends/openid-connect.md
> +`opensearch_security.openid.passphrase` | Passphrase used for a single `private_key` and/or a `pfx`. Optional.
```suggestion
`opensearch_security.openid.passphrase` | Passphrase used for a single `private_key` or a `pfx`. Optional.
```

2023-12-05 17:13 UTC, Naarcha-AWS approved these changes

2023-12-05 19:34 UTC, merged