[DOC] Add workflowIds parameter
opensearch-project/documentation-website pull request #5779
Opened 2023-12-04 19:22 UTC by vagimeli

### Description
Adds workflowIds setting

### Issues Resolved
https://github.com/opensearch-project/documentation-website/issues/5421

### Checklist
- [X] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-12-04 19:25 UTC, vagimeli commented
@eirsep Please tech review and approve the parameter setting changes made in this PR. We are closing a content gap. It should be minimal time effort. Thank you :)

2023-12-08 18:55 UTC, vagimeli commented
> @eirsep

Hi @eirsep: Please provide technical review so that we can publish the updated documentation. Thank you.

2023-12-21 20:09 UTC, vagimeli commented
@hdhalter I'm blocked on this PR because I'm not getting a tech review. I've requested a review using the AWS OpenSearch and OpenSearch community Slack channels. No response after a week. Who is the SDM?

2023-12-21 20:37 UTC, vagimeli commented
@hdhalter Tech review is only needed for line 1346. I've requested tech review via OpenSearch community Slack channel and AWS OpenSearch Slack channel. No response to date. Who is the SDM?

2023-12-21 21:08 UTC, hdhalter commented
> @hdhalter I'm blocked on this PR because I'm not getting a tech review. I've requested a review using the AWS OpenSearch and OpenSearch community Slack channels. No response after a week. Who is the SDM?

I'm checking with @getsaurabh02.

2023-12-21 21:16 UTC, getsaurabh02 commented
Adding @praveensameneni to take a look.

2023-12-21 21:39 UTC, eirsep commented on _observing-your-data/alerting/api.md
> +| `workflowIds` | String | Allows for monitoring the status of multiple chained alerts within a single dashboard. Available in OpenSearch 2.9 or later.
`Allows for monitoring the status of chained alerts from multiple workflows within a single dashboard. Available in OpenSearch 2.9 or later.`

2023-12-21 21:46 UTC, eirsep requested changes
suggested a re-wording for the param description

2024-01-04 12:35 UTC, natebower approved these changes
@vagimeli Just one minor change. Otherwise, LGTM!

2024-01-04 12:35 UTC, natebower commented on _observing-your-data/alerting/api.md
> +| `sortOrder` | String | Defines the results order. Options are `asc` or `desc`. Default is `asc`.
```suggestion
| `sortOrder` | String | Defines the order of results. Options are `asc` or `desc`. Default is `asc`.
```

2024-01-04 19:06 UTC, merged