Add custom_return_attributes to LDAP documentation
opensearch-project/documentation-website pull request #5810
Opened 2023-12-07 15:10 UTC by cwperks

### Description

Adds a setting to the LDAP documentation that was added in OpenSearch 2.4. This attribute allows an admin to specify which attributes to explicitly request from an LDAP server when authenticating a user to prevent the LDAP server from returning all attributes to OpenSearch.

Added in https://github.com/opensearch-project/security/pull/2093

### Issues Resolved

https://github.com/opensearch-project/documentation-website/issues/1248

### Checklist
- [X] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-12-07 18:47 UTC, Naarcha-AWS requested changes

2023-12-07 18:47 UTC, Naarcha-AWS commented on _security/authentication-backends/ldap.md
> +`custom_return_attributes`  | String array. Allows specifying which attributes to request from the LDAP server.
```suggestion
`custom_return_attributes`  | String array. Specifies which attributes to request from the LDAP server.
```

2023-12-07 19:35 UTC, cwperks commented on _security/authentication-backends/ldap.md
> +`custom_return_attributes`  | String array. Allows specifying which attributes to request from the LDAP server.
Updated.

2023-12-08 18:06 UTC, vagimeli commented
@Naarcha-AWS I approved this PR, as it is a quick update.

2023-12-08 21:13 UTC, Naarcha-AWS approved these changes

2023-12-08 21:13 UTC, merged