Updated k-NN lucene engine dimension max count to 16k
opensearch-project/documentation-website pull request #5875
Opened 2023-12-13 22:16 UTC by junqiu-lei

### Description
Updated k-NN lucene engine dimension max count to 16k

### Issues Resolved
Closes https://github.com/opensearch-project/documentation-website/issues/5874

### Checklist
- [ ] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-12-14 18:38 UTC, jmazanec15 approved these changes

2023-12-14 18:46 UTC, Naarcha-AWS requested changes

2023-12-14 18:46 UTC, Naarcha-AWS commented on _search-plugins/knn/approximate-knn.md
> +The `knn_vector` data type supports a vector of floats that can have a dimension count of up to 16,000 for the nmslib, faiss and lucene engines, as set by the dimension mapping parameter.
```suggestion
The `knn_vector` data type supports a vector of floats that can have a dimension count of up to 16,000 for the nmslib, Faiss, and Lucene engines, as set by the dimension mapping parameter.
```

2023-12-19 19:57 UTC, vagimeli commented
@Naarcha-AWS Please provide doc review status update. We need to merge simple content changes within 1-2 days per @hdhalter PR triage process.

2024-01-12 16:54 UTC, Naarcha-AWS approved these changes

2024-01-12 16:54 UTC, Naarcha-AWS commented on _search-plugins/knn/approximate-knn.md
> +The `knn_vector` data type supports a vector of floats that can have a dimension count of up to 16,000 for the nmslib, Faiss, and Lucene engines, as set by the dimension mapping parameter.
```suggestion
The `knn_vector` data type supports a vector of floats that can have a dimension count of up to 16,000 for the NMSLIB, Faiss, and Lucene engines, as set by the dimension mapping parameter.
```

2024-02-01 19:03 UTC, merged