Add deriving metrics from logs use case to Data Prepper
opensearch-project/documentation-website pull request #6248
Opened 2024-01-23 20:27 UTC by vagimeli

### Description
Add deriving metrics from logs use case to Data Prepper

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._

### Checklist
- [X] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-01-23 23:48 UTC, vagimeli commented
@dlvenable This use case PR is ready for your review at availability. Thank you, Melissa

2024-03-06 16:56 UTC, vagimeli commented
@dlvenable At your availability, will you review this use case? It's one of the two last use cases we're transferring from OpenSearch Ingestion. Thank you, Melissa

2024-04-03 19:42 UTC, vagimeli commented
> @dlvenable At your availability, will you review this use case? It's one of the two last use cases we're transferring from OpenSearch Ingestion. Thank you, Melissa

Hi @dlvenable, Is it possible to review this PR by end of week? We need to get this done to address feedback in the benchmark study. Thank you.

2024-04-09 18:13 UTC, vagimeli commented
@dlvenable Following up to get your tech review on this use case carryover from OpenSearch Service Ingestion to Data Prepper. Once we have your approval, I can move this forward to editorial and get it published.

2024-04-09 20:05 UTC, dlvenable requested changes
Thank you @vagimeli !

2024-04-09 20:05 UTC, dlvenable commented on _data-prepper/common-use-cases/metrics-logs.md
> +You can use Data Prepper to derive metrics from logs. The following example pipeline receives incoming logs using the [`http_source` plugin]({{site.url}}{{site.baseurl}}/data-prepper/pipelines/config
```suggestion
You can use Data Prepper to derive metrics from logs. The following example pipeline receives incoming logs using the [`http` source plugin]({{site.url}}{{site.baseurl}}/data-prepper/pipelines/configuration/sources/http-source) and the [`grok` processor]({{site.url}}{{site.baseurl}}/data-prepper/pipelines/configuration/processors/grok/). It then uses the [`aggregate` processor]({{site.url}}{{site.baseurl}}/data-prepper/pipelines/configuration/processors/aggregate/) to extract the metric bytes aggregated over a 30-second window and derives histograms from the results.
```

2024-04-09 20:05 UTC, dlvenable commented on _data-prepper/common-use-cases/metrics-logs.md
> +- `apache-log-pipeline-with-metrics` -– Receives logs through an HTTP client like FluentBit, extracts important values from the logs by matching the value in the `log` key against the [Grok Apache Co
```suggestion
- `apache-log-pipeline-with-metrics` -– Receives logs through an HTTP client like FluentBit, uses `grok` to extract important values from the logs by matching the value in the `log` key against the [Apache Common Log Format](https://httpd.apache.org/docs/2.4/logs.html#accesslog), and then forwards the grokked logs to both the `log-to-metrics-pipeline` pipeline and to an OpenSearch index named `logs`.
```

2024-04-26 10:58 UTC, natebower reviewed
@vagimeli Please see my comments and changes and let me know if you have any questions. Thanks!

2024-04-26 10:58 UTC, natebower commented on _data-prepper/common-use-cases/metrics-logs.md
> +You can use Data Prepper to derive metrics from logs. The following example pipeline receives incoming logs using the [`http` source plugin]({{site.url}}{{site.baseurl}}/data-prepper/pipelines/config
```suggestion
You can use Data Prepper to derive metrics from logs. The following example pipeline receives incoming logs using the [`http` source plugin]({{site.url}}{{site.baseurl}}/data-prepper/pipelines/configuration/sources/http-source) and the [`grok` processor]({{site.url}}{{site.baseurl}}/data-prepper/pipelines/configuration/processors/grok/). It then uses the [`aggregate` processor]({{site.url}}{{site.baseurl}}/data-prepper/pipelines/configuration/processors/aggregate/) to extract the metric bytes aggregated during a 30-second window and derives histograms from the results.
```

2024-04-26 10:58 UTC, natebower commented on _data-prepper/common-use-cases/metrics-logs.md
> +- `apache-log-pipeline-with-metrics` -– Receives logs through an HTTP client like FluentBit, uses `grok` to extract important values from the logs by matching the value in the `log` key against the [
```suggestion
- `apache-log-pipeline-with-metrics` -- Receives logs through an HTTP client like FluentBit, uses `grok` to extract important values from the logs by matching the value in the `log` key against the [Apache Common Log Format](https://httpd.apache.org/docs/2.4/logs.html#accesslog), and then forwards the grokked logs to both the `log-to-metrics-pipeline` pipeline and to an OpenSearch index named `logs`.
```

2024-04-26 10:58 UTC, natebower commented on _data-prepper/common-use-cases/metrics-logs.md
> +The overall pipeline contains two pipelines:
"main" or "primary" instead of "overall"?

2024-04-26 10:58 UTC, natebower commented on _data-prepper/common-use-cases/metrics-logs.md
> +- `log-to-metrics-pipeline` -– Receives the grokked logs from the `apache-log-pipeline-with-metrics` pipeline, aggregates the logs and derives histogram metrics of `bytes` based on the values in the
```suggestion
- `log-to-metrics-pipeline` -- Receives the grokked logs from the `apache-log-pipeline-with-metrics` pipeline, aggregates the logs, and derives histogram metrics of `bytes` based on the values in the `clientip` and `request` keys. Finally, it sends the histogram metrics to an OpenSearch index named `histogram_metrics`.
```

2024-05-13 15:34 UTC, vagimeli commented
@dlvenable Thanks for your review. I've accepted your changes. Do we have any other outstanding items to address before merging?

2024-06-13 15:33 UTC, dlvenable commented on _data-prepper/common-use-cases/metrics-logs.md
> +You can use Data Prepper to derive metrics from logs. The following example pipeline receives incoming logs using the [`http` source plugin]({{site.url}}{{site.baseurl}}/data-prepper/pipelines/config
This writes data to two indexes - one with un-aggregated events and the other derived metrics.

Can we clarify somewhere? You mention below how we use two pipelines. But, maybe we can make this end result more explicit.

2024-06-26 20:05 UTC, vagimeli commented on _data-prepper/common-use-cases/metrics-logs.md
> +This pipeline writes data to two different OpenSearch indexes:
@dlvenable Please review the text added at lines 14--27 and let me know if these additions address your feedback and are accurate. Thank you.

2024-06-28 18:29 UTC, vagimeli commented on _data-prepper/common-use-cases/metrics-logs.md
> +- `apache-log-pipeline-with-metrics`: Receives logs through an HTTP client like FluentBit, uses `grok` to extract important values from the logs by matching the value in the log key against the [Apac
```suggestion
- `apache-log-pipeline-with-metrics`: Receives logs through an HTTP client like FluentBit, using `grok` to extract important values from the logs by matching the value in the log key against the [Apache Common Log Format](https://httpd.apache.org/docs/2.4/logs.html#accesslog). It then forwards the grokked logs to two destinations:
```
```suggestion
- `apache-log-pipeline-with-metrics`: Receives logs through an HTTP client like FluentBit, uses `grok` to extract important values from the logs by matching the value in the log key against the [Apache Common Log Format](https://httpd.apache.org/docs/2.4/logs.html#accesslog). It then forwards the grokked logs to two destinations:
```
```suggestion
- `apache-log-pipeline-with-metrics`: Receives logs through an HTTP client like FluentBit, uses `grok` to extract important values from the logs by matching the value in the log key against the [Apache Common Log Format](https://httpd.apache.org/docs/2.4/logs.html#accesslog). It then forwards the grokked logs to two destinations:
```

2024-07-03 17:54 UTC, dlvenable approved these changes

2024-07-03 18:49 UTC, merged