Updating documentation for new datetime format
opensearch-project/documentation-website pull request #6337
Opened 2024-02-02 06:28 UTC by CaptainDredge

### Description
This PR updates documentation for new datetime format `rfc_3339_lenient` 

### Issues Resolved
Closed #6336

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-02-02 15:34 UTC, hdhalter commented
Thanks, @CaptainDredge ! Did you mean to link this to issue https://github.com/opensearch-project/documentation-website/issues/6308? Is the content ready for doc review?

2024-02-05 06:33 UTC, CaptainDredge commented
> Thanks, @CaptainDredge ! Did you mean to link this to issue https://github.com/opensearch-project/documentation-website/issues/6308? Is the content ready for doc review?

Thanks @hdhalter I've linked to the right issue. The content is ready for review but I'm not able to figure out what exact formatting is required for CI to go green. Is there any automated linter for the docs?

2024-02-05 22:29 UTC, Naarcha-AWS requested changes

2024-02-05 22:29 UTC, Naarcha-AWS commented on _field-types/supported-field-types/date.md
> +`rfc3339_lenient` <br>An RFC3339 compatible datetime formatter which is much faster than other full date lenient formats like `strict_date_optional_time` | Multiple patterns. <br> "YYYY" <br> "2019"
```suggestion
`rfc3339_lenient` <br>An RFC3339 compatible DateTimeFormatter which is much faster than other full date-lenient formats like `strict_date_optional_time` | "YYYY" <br> "2019" <br> "YYYY-MM" <br> "2019-03" <br> "YYYY-MM-DD" <br> "2019-03-23" <br> "YYYY-MM-DDThh:mmTZD" <br> "2019-03-23T21:34Z" <br> "YYYY-MM-DDThh:mm:ssTZD" <br> "2019-03-23T21:34:46Z" <br> "YYYY-MM-DDThh:mm:ss.sTZD" <br> "2019-03-23T21:34:46.123456789-04:00" <br> "YYYY-MM-DDThh:mm:ss,sTZD" "2019-03-23T21:34:46,123456789-04:00"
```

2024-02-06 15:50 UTC, Naarcha-AWS approved these changes

2024-02-06 15:51 UTC, Naarcha-AWS commented
Moving to done, we should update Vale rules so that an `emdash` isn't always required.

2024-02-06 18:43 UTC, kolchfa-aws commented
Endash is required in text but this is literal strings so they should be in code format. Let me make some suggestions.

2024-02-06 18:47 UTC, kolchfa-aws reviewed
Looking at this, we should change all string literals to have code format. @CaptainDredge If you'd like to take this on, that would be great. Otherwise, we can address this in a separate issue. Thanks!

2024-02-06 18:47 UTC, kolchfa-aws commented on _field-types/supported-field-types/date.md
> +`rfc3339_lenient` <br>An RFC3339 compatible DateTimeFormatter which is much faster than other full date-lenient formats like `strict_date_optional_time` | "YYYY" <br> "2019" <br> "YYYY-MM" <br> "2019
```suggestion
`rfc3339_lenient` <br>An RFC3339 compatible DateTimeFormatter which is much faster than other full date-lenient formats like `strict_date_optional_time` | `"YYYY"` <br> `"2019"` <br> `"YYYY-MM"` <br> `"2019-03"` <br> `"YYYY-MM-DD"` <br> `"2019-03-23"` <br> `"YYYY-MM-DDThh:mmTZD"` <br> `"2019-03-23T21:34Z"` <br> `"YYYY-MM-DDThh:mm:ssTZD"` <br> `"2019-03-23T21:34:46Z"` <br> `"YYYY-MM-DDThh:mm:ss.sTZD"` <br> `"2019-03-23T21:34:46.123456789-04:00"` <br> `"YYYY-MM-DDThh:mm:ss,sTZD"` <br> `"2019-03-23T21:34:46,123456789-04:00"`
```

2024-02-08 21:12 UTC, Naarcha-AWS commented on _field-types/supported-field-types/date.md
> +`date_optional_time`<br>`strict_date_optional_time` <br> A generic full date and time. Year is required. Month, day, and time are optional. Time is separated from date by `T`. | Multiple patterns. <b
```suggestion
`date_optional_time`<br>`strict_date_optional_time` <br> A generic full date and time. Year is required. Month, day, and time are optional. Time is separated from date by `T`. | Multiple patterns. <br>`"2019--03--23T21:34:46.123456789--04:00"` <br> `"2019-03-23T21:34:46"` <br> `"2019-03-23T21:34"` <br> `"2019"`
```

2024-02-08 21:20 UTC, merged