[Data Prepper] MAINT: document on disable_refresh secret extension setting
opensearch-project/documentation-website pull request #6384
Opened 2024-02-08 22:26 UTC by chenqi0805

### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._

### Checklist
- [ ] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-02-08 22:30 UTC, dlvenable commented
@chenqi0805 , I changed the target to `data-prepper-2.7` since `disable_refresh` is coming in 2.7.

2024-02-08 22:57 UTC, dlvenable approved these changes
Thanks @chenqi0805 !

2024-02-16 19:07 UTC, Naarcha-AWS commented on _data-prepper/managing-data-prepper/configuring-data-prepper.md
> +refresh_interval | No | Duration | The refreshment interval for AWS secrets extension plugin to poll new secret values. Defaults to `PT1H`. See [Automatically refreshing secrets](#automatically-refre
```suggestion
refresh_interval | No | Duration | The refreshment interval for AWS secrets extension plugin to poll new secret values. Defaults to `PT1H`. For more information. see [Automatically refreshing secrets](#automatically-refreshing-secrets) for details.
```

2024-02-16 19:10 UTC, Naarcha-AWS requested changes

2024-02-16 19:10 UTC, Naarcha-AWS commented on _data-prepper/managing-data-prepper/configuring-data-prepper.md
> +disable_refresh | No | Boolean | The flag to disable AWS secrets extension plugin regular polling on latest secret values. Defaults to `false`. When set to `true`, `refresh_interval` will not be used
```suggestion
disable_refresh | No | Boolean | Disables regular polling on the latest secret values inside the AWS secrets extension plugin. Defaults to `false`. When set to `true`, `refresh_interval` will not be used.
```
```suggestion
disable_refresh | No | Boolean | The flag to disable AWS Secrets extension plugin regular polling on latest secret values. Defaults to `false`. When set to `true`, the `refresh_interval` will not be used.
```

2024-02-16 19:11 UTC, Naarcha-AWS commented on _data-prepper/managing-data-prepper/configuring-data-prepper.md
> +refresh_interval | No | Duration | The refreshment interval for the AWS Secrets extension plugin to poll new secret values. Defaults to `PT1H`. For more information. see [Automatically refreshing sec
```suggestion
refresh_interval | No | Duration | The refreshment interval for the AWS Secrets extension plugin to poll new secret values. Defaults to `PT1H`. For more information, see [Automatically refreshing secrets](#automatically-refreshing-secrets).
```

2024-02-16 19:11 UTC, Naarcha-AWS approved these changes

2024-02-20 21:12 UTC, dlvenable commented
@Naarcha-AWS , Are we good to merge this?

2024-02-26 16:37 UTC, merged