MAINT: Data Prepper opensearch source metrics
opensearch-project/documentation-website pull request #6392
Opened 2024-02-09 20:47 UTC by chenqi0805

### Description
This PR adds opensearch source metrics in data prepper

### Issues Resolved
Closes #6391 

### Checklist
- [ ] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-02-12 17:06 UTC, asifsmohammed approved these changes

2024-02-12 19:21 UTC, dlvenable approved these changes

2024-02-13 20:42 UTC, Naarcha-AWS requested changes

2024-02-13 20:42 UTC, Naarcha-AWS commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +The `opensearch` source includes the following metrics.
```suggestion
The `opensearch` source includes the following metrics:
```

2024-02-13 20:50 UTC, Naarcha-AWS approved these changes

2024-02-13 21:07 UTC, natebower reviewed
@Naarcha-AWS @chenqi0805 Please see my comments and changes and let me know if you have any questions. Thanks!

2024-02-13 21:07 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +- `credentialsChanged`: Measures the number of times the `opensearch` source refreshes basic credentials (i.e. username/password).
```suggestion
- `credentialsChanged`: Measures the number of times that the `opensearch` source refreshes basic credentials (username/password).
```

2024-02-13 21:07 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +- `indexProcessingTime`: Measures the latency of processing an index in seconds by the `opensearch` source plugin.
```suggestion
- `indexProcessingTime`: Measures the `opensearch` source plugin index processing latency, in seconds.
```

2024-02-13 21:07 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +- `bytesReceived`: Measures the distribution of incoming document size in bytes received by the `opensearch` source plugin.
```suggestion
- `bytesReceived`: Measures the size distribution of incoming documents, in bytes, received by the `opensearch` source plugin.
```

2024-02-13 21:07 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +- `bytesProcessed`: Measures the distribution of incoming document size in bytes successfully processed by the `opensearch` source plugin.
```suggestion
- `bytesProcessed`: Measures the size distribution of incoming document, in bytes, successfully processed by the `opensearch` source plugin.
```

2024-02-13 21:07 UTC, natebower commented on _data-prepper/pipelines/configuration/sources/opensearch.md
> +- `bytesProcessed`: Measures the distribution of incoming document size in bytes successfully processed by the `opensearch` source plugin.
Confirm the technical accuracy of my change both here and on the preceding line.

2024-02-16 18:08 UTC, merged