adding more parrams findings API
opensearch-project/documentation-website pull request #6499
Opened 2024-02-23 01:28 UTC by riysaxen-amzn

### Description
Security Analytics Findings API Enhancements

### Issues Resolved
[_List any issues this PR will resolve, e.g. Closes [...]._](https://github.com/opensearch-project/documentation-website/issues/6135)

### Checklist
- [ ] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-02-23 18:56 UTC, hdhalter commented
Thanks so much for submitting this PR, @riysaxen-amzn! Is it ready for review? I assume it should be backported to the lastest release (2.12)?

2024-02-23 23:16 UTC, riysaxen-amzn commented
> Thanks so much for submitting this PR, @riysaxen-amzn! Is it ready for review? I assume it should be backported to the latest release (2.12)?

I couldn't test the changes in my local because of installation issues, other than it is ready for review. The changes shouldn't be backported to latest release 2.12

2024-02-23 23:48 UTC, hdhalter commented
> > Thanks so much for submitting this PR, @riysaxen-amzn! Is it ready for review? I assume it should be backported to the latest release (2.12)?
> 
> I couldn't test the changes in my local because of installation issues, other than it is ready for review. The changes shouldn't be backported to latest release 2.12

OK, are these changes coming in 2.13?

2024-02-27 23:38 UTC, riysaxen-amzn commented
> > > Thanks so much for submitting this PR, @riysaxen-amzn! Is it ready for review? I assume it should be backported to the latest release (2.12)?
> > 
> > 
> > I couldn't test the changes in my local because of installation issues, other than it is ready for review. The changes shouldn't be backported to latest release 2.12
> 
> OK, are these changes coming in 2.13?

yes they'll be in 2.13

2024-03-12 17:29 UTC, Naarcha-AWS commented on _security-analytics/api-tools/alert-finding-api.md
> +`detector_id` | The ID of the detector used to fetch alerts. Optional
```suggestion
`detector_id` | The ID of the detector used to fetch alerts. Optional.
```

2024-03-12 17:31 UTC, Naarcha-AWS requested changes

2024-03-18 20:22 UTC, riysaxen-amzn commented on _security-analytics/api-tools/alert-finding-api.md
> +`startIndex` | The pagination indicator. Optional.
Similar to what we have for Alerts -> https://opensearch.org/docs/latest/security-analytics/api-tools/alert-finding-api/#get-alerts

2024-03-19 18:16 UTC, Naarcha-AWS commented on _security-analytics/api-tools/alert-finding-api.md
> +`detectionType` |  The detection rule type that dictates the retrieval type of the findings. When the detection type is `threat`, it fetches threat intelligence feeds. When it's `rule`, findings are
```suggestion
`detectionType` |  The detection rule type that dictates the retrieval type for the findings. When the detection type is `threat`, it fetches threat intelligence feeds. When the detection type is `rule`, findings are fetched based on the detector's rule. Optional.
```

2024-03-19 18:17 UTC, Naarcha-AWS commented on _security-analytics/api-tools/alert-finding-api.md
> +`severity` |  The severity of the detector rule used to fetch alerts. Severity can be critical|high|medium|low. Optional
```suggestion
`severity` |  The severity of the detector rule used to fetch alerts. Severity can be `critical`, `high`, `medium`, or `low`. Optional
```

2024-03-19 18:17 UTC, Naarcha-AWS approved these changes

2024-03-26 14:40 UTC, natebower reviewed
@riysaxen-amzn @Naarcha-AWS Just a period to be added. Thanks!

2024-03-26 14:40 UTC, natebower commented on _security-analytics/api-tools/alert-finding-api.md
> +`severity` |  The severity of the detector rule used to fetch alerts. Severity can be `critical`, `high`, `medium`, or `low`. Optional
```suggestion
`severity` |  The severity of the detector rule used to fetch alerts. Severity can be `critical`, `high`, `medium`, or `low`. Optional.
```

2024-03-26 17:19 UTC, merged