Tweak compatibility chart with Almalinux8 and remove CentOS8 since already deprecated
opensearch-project/documentation-website pull request #6637
Opened 2024-03-08 23:05 UTC by peterzhuamazon

### Description
Tweak compatibility chart with Almalinux8 and remove CentOS8 since already deprecated

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._

### Checklist
- [ ] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-03-08 23:56 UTC, hdhalter commented
Thanks, @peterzhuamazon ! Should we close this PR? https://github.com/opensearch-project/documentation-website/pull/4980

2024-03-11 14:22 UTC, peterzhuamazon commented
> Thanks, @peterzhuamazon ! Should we close this PR? #4980

Hi @hdhalter, closed old one and will update that once CentOS7 properly deprecated.

2024-03-11 15:20 UTC, hdhalter commented
@peterzhuamazon - Will this be released with 2.13 or should it be backported to 2.12?

2024-03-11 18:12 UTC, peterzhuamazon commented
> @peterzhuamazon - Will this be released with 2.13 or should it be backported to 2.12?

This can go with 2.13 and do not need to backport to 2.12 or before.

2024-03-12 21:53 UTC, hdhalter commented
@Naarcha-AWS , @peterzhuamazon - Can we merge this into main?

2024-03-19 18:13 UTC, Naarcha-AWS commented
@peterzhuamazon: Any update on the status of this one?

2024-03-25 18:10 UTC, hdhalter commented
@Naarcha-AWS - This will not make 2.13 as per Peter. I removed the label.

2024-04-09 17:32 UTC, peterzhuamazon commented
Hi,

@hdhalter @Naarcha-AWS this is ready to review again.

Thanks.

2024-04-09 17:38 UTC, bbarani approved these changes

2024-04-09 18:29 UTC, Naarcha-AWS requested changes

2024-04-09 18:29 UTC, Naarcha-AWS commented on _install-and-configure/install-opensearch/index.md
> +OpenSearch and OpenSearch Dashboards are compatible with Red Hat Enterprise Linux (RHEL) and Debian-based Linux distributions that use [`systemd`](https://en.wikipedia.org/wiki/Systemd), such as Amaz
```suggestion
OpenSearch and OpenSearch Dashboards are compatible with Red Hat Enterprise Linux (RHEL) and Debian-based Linux distributions that use [`systemd`](https://en.wikipedia.org/wiki/Systemd), such as Amazon Linux, and Ubuntu Long-Term Support (LTS). While OpenSearch and OpenSearch Dashboards should work on most Linux distributions, the OpenSearch core team only tests a subset of distributions.
```

2024-04-09 21:38 UTC, peterzhuamazon commented on _install-and-configure/install-opensearch/index.md
> +OpenSearch and OpenSearch Dashboards are compatible with Red Hat Enterprise Linux (RHEL) and Debian-based Linux distributions that use [`systemd`](https://en.wikipedia.org/wiki/Systemd), such as Amaz
Thanks @Naarcha-AWS, updated.

2024-04-09 21:40 UTC, peterzhuamazon commented
Thanks @Naarcha-AWS for the comment I have applied your suggestions.

Please review again

Thanks.

2024-04-10 18:54 UTC, Naarcha-AWS approved these changes

2024-04-10 19:18 UTC, merged