Made changes to create-index documentation to add copy-as-curl option
opensearch-project/documentation-website pull request #6824
Opened 2024-04-02 06:13 UTC by niyatiagg

### Description
Incorporated 1 click copy-as-curl option for create-index documentation

### Issues Resolved
Closes [#6823]

### Checklist
- [X] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-02 12:21 UTC, Naarcha-AWS requested changes

2024-04-02 12:21 UTC, Naarcha-AWS commented on _api-reference/index-apis/delete-index.md
> +****
```suggestion
Do we need these here? 
```

2024-04-02 20:22 UTC, niyatiagg commented on _api-reference/index-apis/delete-index.md
> +****
You are right. Its not!

2024-04-03 12:50 UTC, kolchfa-aws commented on _api-reference/index-apis/delete-index.md
> +Do we need these here?
```suggestion

```

2024-04-03 12:50 UTC, kolchfa-aws approved these changes
LGTM

2024-04-04 15:45 UTC, Naarcha-AWS approved these changes

2024-04-04 15:50 UTC, merged