Add documentation for hardware-accelerated compression codecs.
opensearch-project/documentation-website pull request #6841
Opened 2024-04-02 19:42 UTC by mulugetam

### Description
Adds documentation for [hardware-accelerated compression codecs](https://github.com/opensearch-project/custom-codecs/pull/122) targeting OpenSearch 2.14. 

### Checklist
- [X] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-24 15:29 UTC, Naarcha-AWS requested changes

2024-04-24 15:29 UTC, Naarcha-AWS commented on _im-plugin/index-codecs.md
> +As of OpenSearch 2.14, hardware-accelerated compression codecs for DEFLATE and LZ4 compression algorithms are available. These hardware-accelerated codecs are available on the latest 4th and 5th Gen
```suggestion
As of OpenSearch 2.14, hardware-accelerated compression codecs for the `DEFLATE` and `LZ4` compression algorithms are available. These hardware-accelerated codecs are available on the latest 4th and 5th Gen Intel®️ Xeon®️ processors running Linux kernel 3.10 and later. For all other systems and platforms, the codecs use that platform's corresponding software implementations. 
```

2024-04-24 15:29 UTC, Naarcha-AWS commented on _im-plugin/index-codecs.md
> +The new hard-accelerated codecs can be used by setting the value of `index.codec`:
```suggestion
The new hardware-accelerated codecs can be used by setting one of the following values of the `index.codec` setting:
```

2024-04-24 15:29 UTC, Naarcha-AWS commented on _im-plugin/index-codecs.md
> +* `qat_lz4` (OpenSearch 2.14 and later) -- uses hardware-accelerated LZ4. 
```suggestion
* `qat_lz4` (OpenSearch 2.14 and later): Hardware-accelerated `LZ4`. 
```

2024-04-24 15:29 UTC, Naarcha-AWS commented on _im-plugin/index-codecs.md
> +* `qat_deflate` (OpenSearch 2.14 and later)  -- uses hardware-accelerated DEFLATE.
```suggestion
* `qat_deflate` (OpenSearch 2.14 and later): Hardware-accelerated `DEFLATE`. 
```

2024-04-24 15:29 UTC, Naarcha-AWS commented on _im-plugin/index-codecs.md
> +The `index.codec.compression_level` can be used to specify the compression level for both `qat_lz4` and `qat_deflate`. The new setting, `index.codec.qatmode`, controls the behavior of the hardware ac
```suggestion
The `index.codec.compression_level` setting can be used to specify the compression level for both `qat_lz4` and `qat_deflate`. 

The `index.codec.qatmode` setting controls the behavior of the hardware accelerator and uses on of the following values:
```

2024-04-24 15:29 UTC, Naarcha-AWS commented on _im-plugin/index-codecs.md
> +* `auto` -- uses hardware-accelerated compression. Fails over to use software if the hardware accelerator is not available.
```suggestion
* `auto`: If hardware acceleration fails, the algorithm switches to software acceleration.
```

2024-04-24 15:29 UTC, Naarcha-AWS commented on _im-plugin/index-codecs.md
> +* `hardware` -- use hardware-accelerated compression. An exception is thrown if hardware is not available (guarantees a hardware-only compression).
```suggestion
* `hardware`: Guarantees hardware-only compression. If hardware is not available, an exception occurs until hardware exists.
```

2024-04-24 15:29 UTC, Naarcha-AWS commented on _im-plugin/index-codecs.md
> +Refer to the snapshot section of this page for the implications `index.codec.qatmode` on snapshot and restore.
```suggestion
For information about the `index.codec.qatmode` settings implications on snapshots, see the [Snapshots](#snapshots) section.
```

2024-04-24 15:29 UTC, Naarcha-AWS commented on _im-plugin/index-codecs.md
> +The hardware accelerator that is used is [Intel (R) QAT accelerator](https://www.intel.com/content/www/us/en/architecture-and-technology/intel-quick-assist-technology-overview.html).
```suggestion
For more information about hardware acceleration on Intel, see the [Intel (R) QAT accelerator overview](https://www.intel.com/content/www/us/en/architecture-and-technology/intel-quick-assist-technology-overview.html).
```

2024-04-24 15:29 UTC, Naarcha-AWS commented on _install-and-configure/configuring-opensearch/index-settings.md
> +- `index.codec.qatmode` (String): The hardware acceleration mode used for `qat_lz4` and `qat_deflate` compression codecs:
Lets put this on one line like the other options in the list.

```suggestion
- `index.codec.qatmode` (String): The hardware acceleration mode used for the `qat_lz4` and `qat_deflate` compression codecs. Valid values are `auto` and `hardware`. For more information, see [Index codec settings]({{site.url}}{{site.baseurl}}/im-plugin/index-codecs/). Optional. Default is `auto`. 
```

2024-04-24 15:29 UTC, Naarcha-AWS commented on _install-and-configure/configuring-opensearch/index-settings.md
> +    Valid values are:
```suggestion

```

2024-04-24 15:29 UTC, Naarcha-AWS commented on _install-and-configure/configuring-opensearch/index-settings.md
> +    - `auto`
```suggestion

```

2024-04-24 15:29 UTC, Naarcha-AWS commented on _install-and-configure/configuring-opensearch/index-settings.md
> +    - `hardware`
```suggestion

```

2024-04-24 15:29 UTC, Naarcha-AWS commented on _install-and-configure/configuring-opensearch/index-settings.md
> +    Optional. Default is `auto`. For more information, see [Index codec settings]({{site.url}}{{site.baseurl}}/im-plugin/index-codecs/).
```suggestion

```

2024-04-29 18:10 UTC, Naarcha-AWS approved these changes

2024-04-30 14:47 UTC, natebower commented on _install-and-configure/configuring-opensearch/index-settings.md
> +    - `qat_lz4`(OpenSearch 2.14 and later, on supported systems)
```suggestion
    - `qat_lz4` (OpenSearch 2.14 and later, on supported systems)
```

2024-04-30 14:48 UTC, natebower commented on _install-and-configure/configuring-opensearch/index-settings.md
> +    - `qat_deflate`(OpenSearch 2.14 and later, on supported systems)
```suggestion
    - `qat_deflate` (OpenSearch 2.14 and later, on supported systems)
```

2024-04-30 14:48 UTC, natebower commented on _install-and-configure/configuring-opensearch/index-settings.md
> +    For `zstd`, `zstd_no_dict`, `qat_lz4`, and `qat_deflate` you can specify the compression level in the `index.codec.compression_level` setting. For more information, see [Index codec settings]({{s
```suggestion
For `zstd`, `zstd_no_dict`, `qat_lz4`, and `qat_deflate`, you can specify the compression level in the `index.codec.compression_level` setting. For more information, see [Index codec settings]({{site.url}}{{site.baseurl}}/im-plugin/index-codecs/). Optional. Default is `default`.
```

2024-04-30 14:53 UTC, natebower commented on _install-and-configure/configuring-opensearch/index-settings.md
> +- `index.codec.compression_level` (Integer): The compression level setting provides a trade-off between compression ratio and speed. A higher compression level results in a higher compression ratio (
Please confirm that my changes retain the intended meaning.

2024-04-30 19:06 UTC, merged