Changed documentation for incorrect parameters
opensearch-project/documentation-website pull request #6862
Opened 2024-04-02 21:37 UTC by niyatiagg

### Description
Changed the description of search.cancel_after_time_interval and search.default_search_timeout parameters.

### Issues Resolved
Closes [6843]

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-03 21:27 UTC, Naarcha-AWS requested changes
I'm slightly confused as the why `timeout` is specified in the setting that says `after_time_interval` versus the `search_timeout` setting? Can you provide some additional context here?

2024-04-03 21:27 UTC, Naarcha-AWS commented on _install-and-configure/configuring-opensearch/search-settings.md
> +- `search.cancel_after_time_interval` (Dynamic, time unit): A cluster-level setting that sets the default timeout for all search requests at the coordinating node level. If the `timeout` is specified
```suggestion
- `search.cancel_after_time_interval` (Dynamic, time unit): A cluster-level setting that sets the default timeout for all search requests at the coordinating0node level. If the `timeout` interval is specified in the search request, that interval takes precedent over the configured setting. Default is `-1` (no timeout).
```

2024-04-03 21:27 UTC, Naarcha-AWS commented on _install-and-configure/configuring-opensearch/search-settings.md
> +- `search.default_search_timeout` (Dynamic, time unit): A cluster-level setting that specifies the maximum amount of time that a search request can run before it is canceled at the shard level. After
```suggestion
- `search.default_search_timeout` (Dynamic, time unit): A cluster-level setting that specifies the maximum amount of time that a search request can run before the request is canceled at the shard-level. After the specified time has been reached, the request is stopped and all associated tasks are canceled. Default is `-1`.
```

2024-04-04 18:31 UTC, jainankitk commented
> I'm slightly confused as the why timeout is specified in the setting that says after_time_interval versus the search_timeout setting? Can you provide some additional context here?

The `search.default_search_timeout` setting was originally present, but it only timed out for shard level tasks. We wanted to achieve the same at request level, but did not want to change the behavior of existing setting. Hence, introduced new setting for this. This issue has more context - https://github.com/opensearch-project/OpenSearch#817

2024-04-04 19:36 UTC, jainankitk commented on _install-and-configure/configuring-opensearch/search-settings.md
> +- `search.default_search_timeout` (Dynamic, time unit): A cluster-level setting that specifies the maximum amount of time that a search request can run before the request is canceled at the shard-lev
Can we remove the text `After the specified time has been reached, the request is stopped and all associated tasks are canceled.` from here and add to documentation of `search.cancel_after_time_interval`?

2024-04-04 20:07 UTC, jainankitk approved these changes

2024-04-05 17:16 UTC, Naarcha-AWS approved these changes

2024-04-05 17:19 UTC, merged