Add documentation for primary rebalacing
opensearch-project/documentation-website pull request #7059
Opened 2024-04-30 16:49 UTC by Arpit-Bandejiya

### Description
Add documentation for new setting introduced for Opensearch rebalancing.

### Issues Resolved
#6790 

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-30 17:15 UTC, Arpit-Bandejiya commented
@hdhalter Sorry for the delay. Raised the PR for the two new settings which are raised.

2024-05-01 14:22 UTC, Naarcha-AWS requested changes

2024-05-01 14:22 UTC, Naarcha-AWS commented on _install-and-configure/configuring-opensearch/cluster-settings.md
> +- `cluster.routing.allocation.rebalance.primary.enable` (Boolean): When set to `true`, OpenSearch attempts to evenly rebalance the primary shards between the cluster nodes. Enabling this setting, clu
```suggestion
- `cluster.routing.allocation.rebalance.primary.enable` (Boolean): When set to `true`, OpenSearch attempts to rebalance the primary shards between the cluster nodes. When enabled, the cluster tries to maintain number of primary shards on each node with the maximum buffer defined by the `cluster.routing.allocation.rebalance.primary.buffer` setting . Changing this setting to `false` after it was set to `true` does not invoke the redistribution of primary shards. Default is `false`.
```

2024-05-02 15:45 UTC, Naarcha-AWS approved these changes

2024-05-02 16:12 UTC, natebower reviewed
@Naarcha-AWS Just a few changes. Thanks!

2024-05-02 16:12 UTC, natebower commented on _install-and-configure/configuring-opensearch/cluster-settings.md
> +- `cluster.routing.allocation.rebalance.primary.enable` (Boolean): When set to `true`, OpenSearch attempts to rebalance the primary shards between the cluster nodes. When enabled, the cluster tries t
```suggestion
- `cluster.routing.allocation.rebalance.primary.enable` (Boolean): When set to `true`, OpenSearch attempts to rebalance the primary shards between the cluster nodes. When enabled, the cluster tries to maintain the number of primary shards on each node, with the maximum buffer defined by the `cluster.routing.allocation.rebalance.primary.buffer` setting. Changing this setting to `false` after it was set to `true` does not invoke the redistribution of primary shards. Default is `false`.
```

2024-05-02 18:39 UTC, merged