Docker based development for Jekyll
opensearch-project/documentation-website pull request #7273
Opened 2024-05-30 16:15 UTC by epugh

### Description
Frustrated with Ruby install issues?  Using Docker already?   This let's you contribute documentation improvements without installing Ruby locally.

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._

### Checklist
- [ x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-05-30 17:54 UTC, Naarcha-AWS commented
Love this @epugh! Let me know when it's ready for review.

2024-05-30 19:22 UTC, dtaivpp commented
Ping

2024-05-30 22:48 UTC, epugh commented
Hi all..   So I paired on this with @dtaivpp  and I *think* I have something working.  One potentially controversial decision was to lock the version of Ruby to `3.2.4`.  I polled my local Ruby group on their opinions on if the `Gemfile.lock` should be checked in and the consensus was that yes, it should be, and yes, you should pick a Ruby and stick with it.  By doing this, we don't regenerate the Gemfile.lock constantly, and we can upgrade dependencies more intentionally.   I would LOVE to hear if this works properly on a Linux and Window's environments....

2024-05-30 22:54 UTC, dtaivpp commented
@epugh was the --net=host the solution for your use case? You think we should document that pattern?

2024-05-30 23:01 UTC, epugh commented
> @epugh was the --net=host the solution for your use case? You think we should document that pattern?

I actually didn't a get chance to try that one.....

2024-05-31 19:04 UTC, dtaivpp requested changes
Works on Linux but I had a few comments to make it more usable.

2024-05-31 19:15 UTC, epugh commented on Dockerfile
> +
Probably!   I haven't actually used ENV much in the past, so it felt "new" to me... !  Please make the change!

2024-05-31 19:16 UTC, epugh commented on Dockerfile
> +CMD ["bundle", "exec", "jekyll", "serve", "--host", "0.0.0.0", "--port", "4000", "--incremental", "--livereload", "--trace"]
I love it!

2024-05-31 19:17 UTC, epugh commented on Dockerfile
> +CMD ["bundle", "exec", "jekyll", "serve", "--host", "0.0.0.0", "--port", "4000", "--incremental", "--livereload", "--trace"]
should we add a 1 liner description in the CONTRIBUTING.md file ?   "To run this on your droplet..."???

2024-05-31 19:18 UTC, dtaivpp commented on Dockerfile
> +CMD ["bundle", "exec", "jekyll", "serve", "--host", "0.0.0.0", "--port", "4000", "--incremental", "--livereload", "--trace"]
100% I'll add that along with a bit more about the pattern.

2024-05-31 19:36 UTC, dtaivpp approved these changes
@kolchfa-aws I reviewed these and confirmed the steps outlined work and are documented correctly!

2024-05-31 20:58 UTC, Naarcha-AWS commented
Test on Windows was successful.

2024-05-31 20:59 UTC, Naarcha-AWS commented
@epugh: Once you take this out of draft mode, I'll give the language and formatting a proper review. Ping me when you're ready.

2024-05-31 21:22 UTC, epugh commented
@Naarcha-AWS  it's no longer draft!   THanks for testing on windows!

2024-05-31 22:40 UTC, kolchfa-aws commented
Thanks for validating the steps, @dtaivpp! Much appreciated. Let's get a review from @AMoo-Miki too (specifically fixing the Ruby version).

2024-06-03 19:06 UTC, Naarcha-AWS requested changes
This changes suggested make the formatting more in line with the next section.

2024-06-03 19:06 UTC, Naarcha-AWS commented on CONTRIBUTING.md
> +#### Setting up your Docker based copy of the repository
```suggestion
#### Setting up a Docker-based copy of the repository

```

2024-06-03 19:06 UTC, Naarcha-AWS commented on CONTRIBUTING.md
> +This assumes you have Docker installed.
```suggestion
If you have Docker installed, you can use Docker to test any major changes to the documentation website locally by using the following steps:
```

2024-06-03 19:06 UTC, Naarcha-AWS commented on CONTRIBUTING.md
> +1. [Fork this repository](https://docs.github.com/en/get-started/quickstart/fork-a-repo) and clone your fork.
```suggestion
1. [Fork this repository](https://docs.github.com/en/get-started/quickstart/fork-a-repo) and clone your fork in the directory of your choice.
```

2024-06-03 19:06 UTC, Naarcha-AWS commented on CONTRIBUTING.md
> +1. Build the documentation website Jekyll image via: `docker build -t documentation-website .`
```suggestion
1. Build the documentation website Jekyll image by using the following command: 

    ```
    docker build -t documentation-website .
    ```
```

2024-06-03 19:06 UTC, Naarcha-AWS commented on CONTRIBUTING.md
> +1. Start Jekyll via: `docker run -p 4000:4000 -v $(pwd):/app documentation-website`
```suggestion
1. Start Jekyll from inside the image using the following command: 

   ```
   docker run -p 4000:4000 -v $(pwd):/app documentation-website
   ```
```

2024-06-03 19:06 UTC, Naarcha-AWS commented on CONTRIBUTING.md
> +Be aware that it takes a while to build the site the first time, eventually you will see `Server running... press ctrl-c to stop`.
```suggestion
When building the site for the first time, it'll take some time for the site to build. When your Jekyll instance is ready, you will see `Server running... press ctrl-c to stop`.
```

2024-06-04 21:25 UTC, Naarcha-AWS commented
@epugh: Per the advice of @AMoo-Miki, the `gemfile` shouldn't prevent someone from using a different version of ruby if they so choose. One alternative is to make a gemfile specific for Docker.

2024-07-11 00:04 UTC, hdhalter commented
@dtaivpp , @epugh - Is Miki's comment a blocker for pushing this up?

2024-07-11 15:07 UTC, dtaivpp commented
@hdhalter I think that comes down to the preferences of the project. It's pretty standard to standardize on a single version of ruby. That way changes that are made in one persons environment should be guaranteed to work in production with the same ruby version. 

@AMoo-Miki I'm curious what advantage there is to allowing users to use any ruby version they'd like. That feels like a risk

2024-08-22 21:07 UTC, epugh commented
Just went to add some docs and ran `build.sh` and hit the 

```
Could not find jekyll-last-modified-at-1.3.0, i18n-1.14.3, rouge-4.2.0, posix-spawn-0.3.15, public_suffix-5.0.4, concurrent-ruby-1.2.3, sass-embedded-1.71.1-x86_64-darwin, ffi-1.16.3, google-protobuf-3.25.3-x86_64-darwin, rb-inotify-0.10.1 in locally installed gems
```
message.  

The big change that impacts non Docker users in this set up is that we check into the repo `Gemfile.lock` and specify the version of Ruby to use, instead of leaving it open....    So you have to use a specific Ruby...  Though we will then know all the versions of the gems you use ;-).   This is my preference.

If that is too much, I could look at having Docker install ruby and the gems at start up time.  That would make firing up the docker image a lot slower, but might be a more gentle introduction of Docker into the tool chain....    Thoughts @AMoo-Miki ?

2024-10-16 13:12 UTC, epugh commented
This was solved in #8220!  Thanks @hainenber for getting this problem solved!

2024-10-16 13:12 UTC, closed without merging