adding oidc docker example with keycloak #1566
opensearch-project/documentation-website pull request #7372
Opened 2024-06-12 13:56 UTC by AntonEliatra

### Description
Adding oidc docker example with keycloak configuration to provide roles

### Issues Resolved
Part of issues on https://github.com/opensearch-project/documentation-website/issues/1566

### Version
all

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-06-13 13:36 UTC, scrawfor99 approved these changes

2024-06-14 20:04 UTC, Naarcha-AWS requested changes

2024-06-14 20:04 UTC, Naarcha-AWS commented on _security/authentication-backends/openid-connect.md
> +  - `opensearch_dashboards.yml` configured to point to Keycloak for authentication
```suggestion
  - `opensearch_dashboards.yml` should point to Keycloak for authentication. Make sure that the `opensearch_security.openid.connect_url` setting points to the URL of the realm.

2024-06-14 20:04 UTC, Naarcha-AWS commented on _security/authentication-backends/openid-connect.md
> +6. Access OpenSearch Dashboards on `http://localhost:5601` and login with user `testuser` and password `testpasword` (which is configured in `new-realm.json`). Upon login the `testuser` receives back
```suggestion
6. Access OpenSearch Dashboards on `http://localhost:5601` and login with user `testuser` and password `testpassword` configured in `new-realm.json`. After logging in the `testuser` receives backend role `admin` from Keycloak, which is mapped to the `all_access` OpenSearch role. These backend roles can be managed using the Keycloak Administrative Console at http://localhost:8080, using username `admin` and password `admin`.
```

2024-06-25 18:33 UTC, Naarcha-AWS commented on _security/authentication-backends/openid-connect.md
> +6. Access OpenSearch Dashboards on `http://localhost:5601` and login with user `testuser` and password `testpassword` configured in `new-realm.json`. After logging in the `testuser` receives backend
```suggestion
6. Access OpenSearch Dashboards on `http://localhost:5601` and login with user `testuser` and password `testpassword` configured in the `new-realm.json` file. 

After logging in the `testuser` receives backend role `admin` from Keycloak, which is mapped to the `all_access` OpenSearch role. These backend roles can be managed using the Keycloak Administrative Console at http://localhost:8080, using username `admin` and password `admin`.
```

2024-06-26 17:06 UTC, Naarcha-AWS approved these changes

2024-06-26 17:12 UTC, natebower reviewed
@Naarcha-AWS @AntonEliatra Please see my changes and let me know if you have any questions. Thanks!

2024-06-26 17:12 UTC, natebower commented on _security/authentication-backends/openid-connect.md
> +  - `docker-compose.yml` defines a single OpenSearch node, OpenSearch Dashboards and Keycloak server.
```suggestion
  - `docker-compose.yml` defines a single OpenSearch node, OpenSearch Dashboards, and Keycloak server.
```

2024-06-26 17:12 UTC, natebower commented on _security/authentication-backends/openid-connect.md
> +  - `new-realm.json` specifies the details for the [realm](https://www.keycloak.org/docs/latest/server_admin/#core-concepts-and-terms). In this example, the realm is named `new`.
```suggestion
  - `new-realm.json` specifies the details of the [realm](https://www.keycloak.org/docs/latest/server_admin/#core-concepts-and-terms). In this example, the realm is named `new`.
```

2024-06-26 17:12 UTC, natebower commented on _security/authentication-backends/openid-connect.md
> +6. Access OpenSearch Dashboards on `http://localhost:5601` and login with user `testuser` and password `testpassword` configured in the `new-realm.json` file.
```suggestion
6. Access OpenSearch Dashboards at `http://localhost:5601` and log in with username `testuser` and password `testpassword` configured in the `new-realm.json` file. 
```

2024-06-26 17:12 UTC, natebower commented on _security/authentication-backends/openid-connect.md
> +After logging in the `testuser` receives backend role `admin` from Keycloak, which is mapped to the `all_access` OpenSearch role. These backend roles can be managed using the Keycloak Administrative
```suggestion
After logging in, the `testuser` receives the backend role `admin` from Keycloak, which is mapped to the `all_access` OpenSearch role. These backend roles can be managed using the Keycloak Administrative Console at http://localhost:8080, using username `admin` and password `admin`.
```

2024-06-26 18:50 UTC, merged