setting-envars-docs #3582
opensearch-project/documentation-website pull request #7400
Opened 2024-06-17 14:46 UTC by AntonEliatra

### Description
Expanding on options to configure envars in OpenSearch

### Issues Resolved
Partly closes https://github.com/opensearch-project/documentation-website/issues/3582

### Version
all

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-06-24 20:10 UTC, scrawfor99 approved these changes

2024-07-03 19:04 UTC, Naarcha-AWS requested changes

2024-07-03 19:04 UTC, Naarcha-AWS commented on _install-and-configure/configuring-opensearch/index.md
> +You can specify environment variables in different ways.
```suggestion
You can specify environment variables in the following ways.
```

2024-07-03 19:04 UTC, Naarcha-AWS commented on _install-and-configure/configuring-opensearch/index.md
> +You can configure the environment variables directly in shell before starting OpenSearch:
```suggestion
You can configure the environment variables directly in a shell environment before starting OpenSearch, as shown in the following example:
```

2024-07-03 19:04 UTC, Naarcha-AWS commented on _install-and-configure/configuring-opensearch/index.md
> +When running OpenSearch as a service managed by systemd, you can specify environment variables in the service file:
```suggestion
When running OpenSearch as a service managed by `systemd`, you can specify environment variables in the service file, as shown in the following example:
```

2024-07-03 19:04 UTC, Naarcha-AWS commented on _install-and-configure/configuring-opensearch/index.md
> +After creating or modifying the file, reload the systemd configuration and restart the service:
```suggestion
After creating or modifying the file, reload the systemd configuration and restart the service using the following command:
```

2024-07-03 19:04 UTC, Naarcha-AWS commented on _install-and-configure/configuring-opensearch/index.md
> +When running OpenSearch in Docker, you can specify environment variables using the -e option with Docker run:
```suggestion
When running OpenSearch in Docker, you can specify environment variables using the -e option with Docker run, as shown in the following command:
```

2024-07-05 13:33 UTC, Naarcha-AWS approved these changes

2024-07-09 15:47 UTC, natebower reviewed
@Naarcha-AWS @AntonEliatra  A few comments for you. Thanks!

2024-07-09 15:47 UTC, natebower commented on _install-and-configure/configuring-opensearch/index.md
> +### Arguments as start up
Should "as" be "at"? Also, if "startup" is a noun, it should be one word with no space.

2024-07-09 15:47 UTC, natebower commented on _install-and-configure/configuring-opensearch/index.md
> +When running OpenSearch in Docker, you can specify environment variables using the -e option with Docker run, as shown in the following command:
Should it be "the `-e` option with `docker run`"?

2024-07-09 16:02 UTC, AntonEliatra commented
@natebower good catch, thats updated now

2024-07-09 16:47 UTC, merged