Fix format issue for the split ingest processor documentation
opensearch-project/documentation-website pull request #7695
Opened 2024-07-12 02:48 UTC by gaobinlong

### Description

Fix the format issue in the documentation of split ingest processor.

### Issues Resolved

https://github.com/opensearch-project/documentation-website/issues/7694

### Version
All versions.

### Frontend features
_If you're submitting documentation for an OpenSearch Dashboards feature, add a video that shows how a user will interact with the UI step by step. A voiceover is optional._ 

### Checklist
- [ ] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-12 13:51 UTC, Naarcha-AWS commented on _ingest-pipelines/processors/split.md
> +| Parameter  | Required/Optional  | Description  |
```suggestion
Parameter  | Required/Optional  | Description 
```

2024-07-12 13:52 UTC, Naarcha-AWS requested changes

2024-07-12 13:52 UTC, Naarcha-AWS commented on _ingest-pipelines/processors/split.md
> +|---|---|---|
```suggestion
:--- | :--- | :--- 
```

2024-07-12 13:52 UTC, Naarcha-AWS commented on _ingest-pipelines/processors/split.md
> +`field` | Required | The field containing the string to be split. |
```suggestion
`field` | Required | The field containing the string to be split. 
```

2024-07-12 13:52 UTC, Naarcha-AWS commented on _ingest-pipelines/processors/split.md
> +`separator` | Required | The delimiter used to split the string. This can be a regular expression pattern. |
```suggestion
`separator` | Required | The delimiter used to split the string. This can be a regular expression pattern. 
```

2024-07-12 13:52 UTC, Naarcha-AWS commented on _ingest-pipelines/processors/split.md
> +`preserve_field` | Optional | If set to `true`, preserves empty trailing fields (for example, `''`) in the resulting array. If set to `false`, empty trailing fields are removed from the resulting arr
```suggestion
`preserve_field` | Optional | If set to `true`, preserves empty trailing fields (for example, `''`) in the resulting array. If set to `false`, empty trailing fields are removed from the resulting array. Default is `false`. 
```

2024-07-12 13:52 UTC, Naarcha-AWS commented on _ingest-pipelines/processors/split.md
> +`target_field` | Optional | The field where the array of substrings is stored. If not specified, then the field is updated in-place. |
```suggestion
`target_field` | Optional | The field where the array of substrings is stored. If not specified, then the field is updated in-place. 
```

2024-07-12 13:52 UTC, Naarcha-AWS commented on _ingest-pipelines/processors/split.md
> +`ignore_missing` | Optional	| Specifies whether the processor should ignore documents that do not contain the specified field. If set to `true`, then the processor ignores missing values in the field
```suggestion
`ignore_missing` | Optional	| Specifies whether the processor should ignore documents that do not contain the specified field. If set to `true`, then the processor ignores missing values in the field and leaves the `target_field` unchanged. Default is `false`.  
```

2024-07-12 13:52 UTC, Naarcha-AWS commented on _ingest-pipelines/processors/split.md
> +`description` | Optional | A brief description of the processor. |
```suggestion
`description` | Optional | A brief description of the processor. 
```

2024-07-12 13:52 UTC, Naarcha-AWS commented on _ingest-pipelines/processors/split.md
> +`if` | Optional | A condition for running the processor. |
```suggestion
`if` | Optional | A condition for running the processor. 
```

2024-07-12 13:52 UTC, Naarcha-AWS commented on _ingest-pipelines/processors/split.md
> +`ignore_failure` | Optional | Specifies whether the processor continues execution even if it encounters an error. If set to `true`, then failures are ignored. Default is `false`. |
```suggestion
`ignore_failure` | Optional | Specifies whether the processor continues execution even if it encounters an error. If set to `true`, then failures are ignored. Default is `false`. 
```

2024-07-12 13:52 UTC, Naarcha-AWS commented on _ingest-pipelines/processors/split.md
> +`on_failure` | Optional | A list of processors to run if the processor fails. |
```suggestion
`on_failure` | Optional | A list of processors to run if the processor fails. 
```

2024-07-12 13:52 UTC, Naarcha-AWS commented on _ingest-pipelines/processors/split.md
> +`tag` | Optional | An identifier tag for the processor. Useful for debugging in order to distinguish between processors of the same type. |
```suggestion
`tag` | Optional | An identifier tag for the processor. Useful for debugging in order to distinguish between processors of the same type. 
```

2024-07-12 21:44 UTC, hdhalter approved these changes

2024-07-15 20:08 UTC, Naarcha-AWS approved these changes

2024-07-16 00:55 UTC, merged