Move bulk API's batch_size parameter to processors
opensearch-project/documentation-website pull request #7719
Opened 2024-07-16 10:16 UTC by chishui

### Description
1. Mark `batch_size` parameter of bulk API to deprecated
2. Change `batch_size` parameter's default value from 1 to 2147483647
3. Add  `batch_size` to `text_embedding` and `sparse_encoding` processors

### Issues Resolved
https://github.com/opensearch-project/documentation-website/issues/7717

### Version
2.16

### Frontend features
_If you're submitting documentation for an OpenSearch Dashboards feature, add a video that shows how a user will interact with the UI step by step. A voiceover is optional._ 

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-16 23:14 UTC, hdhalter commented
Thanks, @chishui!! Is this ready for a doc review?

2024-07-17 01:28 UTC, chishui commented
@hdhalter I'll post a comment here once this PR is merged and the doc is ready for review, thanks!

2024-07-23 06:51 UTC, chishui commented
@hdhalter @Naarcha-AWS  The PR this documentation depending on has been merged

2024-07-23 17:56 UTC, Naarcha-AWS requested changes

2024-07-23 17:56 UTC, Naarcha-AWS commented on _api-reference/document-apis/bulk.md
> +batch_size | Integer | (Deprecated) Specifies the number of documents to be batched and sent to an ingest pipeline to be processed together. Default is `2147483647` (documents are ingested by an inge
```suggestion
batch_size | Integer | **(Deprecated)** Specifies the number of documents to be batched and sent to an ingest pipeline to be processed together. Default is `2147483647` (documents are ingested by an ingest pipeline all at once). If the bulk request doesn't explicitly specify an ingest pipeline or the index doesn't have a default ingest pipeline, then this parameter is ignored. Only documents with `create`, `index`, or `update` actions can be grouped into batches.
```

2024-07-23 17:56 UTC, Naarcha-AWS commented on _ingest-pipelines/processors/sparse-encoding.md
> +`batch_size` | Integer | Optional | Specifies the number of documents to be batched and processed each time. Default value is 1. |
```suggestion
`batch_size` | Integer | Optional | Specifies the number of documents to be batched and processed each time. Default is `1`. |
```

2024-07-23 17:56 UTC, Naarcha-AWS commented on _ingest-pipelines/processors/text-embedding.md
> +`batch_size` | Integer | Optional | Specifies the number of documents to be batched and processed each time. Default value is 1. |
```suggestion
`batch_size` | Integer | Optional | Specifies the number of documents to be batched and processed each time. Default is `1`. |
```

2024-07-24 14:26 UTC, Naarcha-AWS approved these changes

2024-07-25 18:31 UTC, natebower reviewed
@Naarcha-AWS @chishui Just a couple of minor additions. Thanks!

2024-07-25 18:31 UTC, natebower commented on _ml-commons-plugin/remote-models/batch-ingestion.md
> +When using [Bulk API]({{site.url}}{{site.baseurl}}/api-reference/document-apis/bulk/) to ingest documents, processors that support batch ingestion will split documents into batches and send each batc
```suggestion
When using the [Bulk API]({{site.url}}{{site.baseurl}}/api-reference/document-apis/bulk/) to ingest documents, processors that support batch ingestion will split documents into batches and send each batch of documents to an externally hosted model in a single request.
```

2024-07-25 18:31 UTC, natebower commented on _ml-commons-plugin/remote-models/batch-ingestion.md
> +To ingest documents in bulk, call the Bulk API and provide the `pipeline` parameter. If you don't provide a `pipeline` parameter, the default ingest pipeline for the index will be used for ingestion:
```suggestion
To ingest documents in bulk, call the Bulk API and provide the `pipeline` parameter. If you don't provide a `pipeline` parameter, then the default ingest pipeline for the index will be used for ingestion:
```

2024-07-29 17:39 UTC, merged