add note regarding required use of TLS transport
opensearch-project/documentation-website pull request #804
Opened 2022-07-15 05:54 UTC by dvas0004

### Description
"basic usage" doesn't mention that the securityadmin.sh command will fail outright if `plugins.security.ssl.http.enabled` is set to `false`

### Issues Resolved
N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-07-15 16:10 UTC, Naarcha-AWS commented
@dvas0004: Your commit requires the DCO sign-off to pass the PR check.
See [fix DCO](https://github.com/src-d/guide/blob/9171d013c648236c39faabcad8598be3c0cf8f56/developer-community/fix-DCO.md#how-to-add-sign-offs-retroactively) for details.

2022-07-19 04:08 UTC, dvas0004 commented
DCO sign off added

2022-07-20 17:32 UTC, Naarcha-AWS requested changes

2022-07-20 17:32 UTC, Naarcha-AWS commented on _security-plugin/configuration/security-admin.md
> +**Note:** `securityadmin.sh` requires that SSL/TLS transport is enabled on your opensearch cluster. In other words, make sure that the following is set in `opensearch.yml` before proceeding:
```suggestion
`securityadmin.sh` requires that SSL/TLS transport is enabled on your opensearch cluster. In other words, make sure that the `plugins.security.ssl.http.enabled: true` is set in `opensearch.yml` before proceeding.
{: .note}
```

2022-07-20 17:33 UTC, Naarcha-AWS commented on _security-plugin/configuration/security-admin.md
> +**Note:** `securityadmin.sh` requires that SSL/TLS transport is enabled on your opensearch cluster. In other words, make sure that the following is set in `opensearch.yml` before proceeding:
Let's rework this to make sure the note renders properly.

2022-07-20 17:34 UTC, Naarcha-AWS reviewed
A couple of small tweaks, than we should be good to go!

2022-07-20 17:34 UTC, Naarcha-AWS commented on _security-plugin/configuration/security-admin.md
> +`plugins.security.ssl.http.enabled: true`
Remove this line and add it to the note as shown in my previous comment.

2022-08-23 16:14 UTC, cwillum commented on _security-plugin/configuration/security-admin.md
> +`plugins.security.ssl.http.enabled: true`
I see now the plan is to remove line 85, which takes care of both my concerns. Will approve this.

2022-08-23 16:14 UTC, cwillum approved these changes

2022-09-01 16:19 UTC, merged