Add keep type docs #8063
opensearch-project/documentation-website pull request #8122
Opened 2024-08-29 17:03 UTC by AntonEliatra

### Description
Add keep type docs

### Issues Resolved
Closes https://github.com/opensearch-project/documentation-website/issues/8063

### Version
All

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-08-29 20:00 UTC, vagimeli commented
@udabhas Will you review this PR for technical accuracy? Thank you.

2024-10-03 16:10 UTC, vagimeli commented
> @udabhas Will you review this PR for technical accuracy? Thank you.

@udabhas @varun-lodaya This is over a month old. We need tech review approval to move it forward in the documentation process. Please review this week or provide a peer who can review it. Thank you.

2024-11-11 20:24 UTC, kolchfa-aws commented on _analyzers/token-filters/keep-types.md
> +The `keep_types` token filter is a type of token filter used in text analysis to control which token types are kept or discarded during analysis. Different tokenizers produce different token types, f
```suggestion
The `keep_types` token filter is a type of token filter used in text analysis to control which token types are kept or discarded. Different tokenizers produce different token types, for example `word`, `<NUM>`, or `<ALPHANUM>`.
```

2024-11-11 20:32 UTC, kolchfa-aws requested changes
Thank you, @AntonEliatra! Please see my comments and let me know if you have any questions.

2024-11-12 16:45 UTC, AntonEliatra commented on _analyzers/token-filters/keep-types.md
> +  "text": "Hello, world! This is an example."
done

2024-11-12 16:46 UTC, AntonEliatra commented
@kolchfa-aws the comments have now been addressed

2024-11-12 16:47 UTC, kolchfa-aws approved these changes
Thanks! LGTM

2024-11-12 17:09 UTC, natebower reviewed
@AntonEliatra @kolchfa-aws One comment and one change. Thanks!

2024-11-12 17:09 UTC, natebower commented on _analyzers/token-filters/keep-types.md
> +The `keep_types` token filter is a type of token filter used in text analysis to control which token types are kept or discarded. Different tokenizers produce different token types, for example `<HOS
```suggestion
The `keep_types` token filter is a type of token filter used in text analysis to control which token types are kept or discarded. Different tokenizers produce different token types, for example, `<HOST>`, `<NUM>`, or `<ALPHANUM>`.
```

2024-11-12 17:09 UTC, natebower commented on _analyzers/token-filters/keep-types.md
> +`types` | Required | List of strings | List of token types to be kept or removed (determined by the `mode`).
Nit: On line 10 we use "discarded" instead of "removed". We should probably use the same word in both instances.

2024-11-12 18:06 UTC, kolchfa-aws commented on _analyzers/token-filters/keep-types.md
> +`types` | Required | List of strings | List of token types to be kept or removed (determined by the `mode`).
```suggestion
`types` | Required | List of strings | List of token types to be kept or discarded (determined by the `mode`).
```

2024-11-12 18:10 UTC, merged