Data Stream support for Audit- Log
opensearch-project/documentation-website pull request #8356
Opened 2024-09-24 09:24 UTC by tmanninger

### Description
Documentation for the MR https://github.com/opensearch-project/security/pull/4257

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-01 19:57 UTC, Naarcha-AWS commented
@tmanninger: Is there a doc issue associated with this PR?

2024-10-15 19:12 UTC, Naarcha-AWS requested changes

2024-10-15 19:12 UTC, Naarcha-AWS commented on _security/audit-logs/storage-types.md
> +## Internal Opensearch Data Stream
```suggestion
## Internal OpenSearch data streams
```

2024-10-15 19:12 UTC, Naarcha-AWS commented on _security/audit-logs/storage-types.md
> +### Basics settings
```suggestion
### Basic settings
```

2024-10-15 19:12 UTC, Naarcha-AWS commented on _security/audit-logs/storage-types.md
> +The type `internal_opensearch_data_stream` have some additional configuration paramters.
```suggestion
You can configure the `internal_opensearch_data_stream` type with the following configuration parameters.
```

2024-10-15 19:12 UTC, Naarcha-AWS commented on _security/audit-logs/storage-types.md
> +`plugins.security.audit.config.data_stream.name` | String | Name of the auditlog Data Stream. The Default is `opensearch-security-auditlog`.
```suggestion
`plugins.security.audit.config.data_stream.name` | String | The name of the audit log data stream. Default is `opensearch-security-auditlog`.
```

2024-10-15 19:12 UTC, Naarcha-AWS commented on _security/audit-logs/storage-types.md
> +`plugins.security.audit.config.data_stream.template.manage` | Boolean | If enabled, the template for the Data Stream is managed by Opensearch. The Default is `true`.
```suggestion
`plugins.security.audit.config.data_stream.template.manage` | Boolean | If `true`, the template for the data stream is managed by Opensearch. Default is `true`.
```

2024-10-15 19:12 UTC, Naarcha-AWS commented on _security/audit-logs/storage-types.md
> +`plugins.security.audit.config.data_stream.template.name` | String | Name of the template. The Default is `opensearch-security-auditlog`.
```suggestion
`plugins.security.audit.config.data_stream.template.name` | String | The name of the data stream template. Default is `opensearch-security-auditlog`.
```

2024-10-15 19:12 UTC, Naarcha-AWS commented on _security/audit-logs/storage-types.md
> +`plugins.security.audit.config.data_stream.template.number_of_replicas` | Integer | Number of replicas for the Data Stream. The default is `0`.
```suggestion
`plugins.security.audit.config.data_stream.template.number_of_replicas` | Integer | The number of replicas for the data stream. Default is `0`.
```

2024-10-15 19:12 UTC, Naarcha-AWS commented on _security/audit-logs/storage-types.md
> +`plugins.security.audit.config.data_stream.template.number_of_shards` | Integer | Number of Shards for the Data Stream. The default is `1`.
```suggestion
`plugins.security.audit.config.data_stream.template.number_of_shards` | Integer | The number of shards for the data stream. Default is `1`.
```

2024-10-28 17:12 UTC, Naarcha-AWS requested changes

2024-10-28 17:12 UTC, Naarcha-AWS commented on _security/audit-logs/storage-types.md
> +`internal_opensearch_data_stream`, `external_opensearch`, `webhook`, and `log4j` all have additional configuration options. Details follow.
```suggestion
`internal_opensearch_data_stream`, `external_opensearch`, `webhook`, and `log4j` can be customized with additional configuration options. For more information, see [Internal OpenSearch data streams](#internal-opensearch-data-streams).
```

2024-10-28 17:12 UTC, Naarcha-AWS commented on _security/audit-logs/storage-types.md
> +### Basic settings
Will there be any additional settings called out in this section in the future?

2024-10-28 17:12 UTC, Naarcha-AWS commented on _security/audit-logs/storage-types.md
> +`plugins.security.audit.config.data_stream.template.manage` | Boolean | If `true`, the template for the data stream is managed by Opensearch. Default is `true`.
```suggestion
`plugins.security.audit.config.data_stream.template.manage` | Boolean | When `true`, the template for the data stream is managed by Opensearch. Default is `true`.
```

2024-10-28 18:53 UTC, Naarcha-AWS commented on _security/audit-logs/storage-types.md
> +### Basic settings
```suggestion

```

2024-10-28 18:54 UTC, Naarcha-AWS commented
@natebower: This is ready for editorial review.

2024-10-28 19:09 UTC, Naarcha-AWS approved these changes

2024-10-29 10:09 UTC, natebower reviewed
@Naarcha-AWS @tmanninger Just a minor deletion. Thanks!

2024-10-29 10:09 UTC, natebower commented on _security/audit-logs/storage-types.md
> +You can configure the `internal_opensearch_data_stream` type with the following configuration parameters.
```suggestion
You can configure the `internal_opensearch_data_stream` type with the following parameters.
```

2024-10-29 19:32 UTC, merged