Add 'Clone Snapshot' API Documentation
opensearch-project/documentation-website pull request #8371
Opened 2024-09-24 21:31 UTC by Reiyadowns

### Description
Adds documentation for the 'Clone Snapshot' API

### Issues Resolved
Addresses half of issue #2111
(In combination with the branch 'add-cleanup-snapshot-docs', the issue is fully addressed and can be closed)

### Version
Applies to all versions.

### Checklist
- [ ] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2025-02-20 15:59 UTC, Naarcha-AWS commented
@Reiyadowns: We recently automated some of our API documentation based on OpenSearch API specification. I'm going to adjust this PR to add those automation markers then get this merged.

2025-03-28 14:23 UTC, Naarcha-AWS commented on _api-reference/snapshots/clone-snapshot.md
> +# Clone Snapshot
```suggestion
# Clone snapshot
```

2025-03-28 14:24 UTC, Naarcha-AWS commented on _api-reference/snapshots/clone-snapshot.md
> +Upon success, the request returns the following json object:
```suggestion
Upon success, the request returns the following JSON object:
```

2025-03-28 14:28 UTC, Naarcha-AWS approved these changes

2025-03-28 14:49 UTC, Naarcha-AWS commented on _api-reference/snapshots/clone-snapshot.md
> +Upon success, the request returns the following JSON object:
```suggestion
The following example shows an API response:
```

2025-03-28 15:26 UTC, natebower requested changes
@Naarcha-AWS Please see my comments and changes and tag me for approval when addressed. Thanks!

2025-03-28 15:26 UTC, natebower commented on _api-reference/snapshots/clone-snapshot.md
> +Creates a clone of all or part of a snapshot, in the same repository as the original.
```suggestion
Creates a clone of all or part of a snapshot in the same repository as the original.
```

2025-03-28 15:26 UTC, natebower commented on _api-reference/snapshots/clone-snapshot.md
> +| `repository` | **Required** | String | The name of repository which will contain the snapshots clone. |
```suggestion
| `repository` | **Required** | String | The name of repository that will contain the snapshot clone. |
```

2025-03-28 15:26 UTC, natebower commented on _api-reference/snapshots/clone-snapshot.md
> +The following example shows an API response:
Can we be a bit more descriptive here about what the response shows?

2025-03-28 15:51 UTC, natebower approved these changes
@Naarcha-AWS LGTM

2025-03-28 16:15 UTC, Naarcha-AWS approved these changes

2025-03-28 16:15 UTC, merged