[DOC] Tokenizer - Edge-n-gram
opensearch-project/documentation-website pull request #8378
Opened 2024-09-25 17:28 UTC by leanneeliatra

### Description
Addition of the Tokenizer Edge-n-gram documentation, to the Analyzers section.

### Issues Resolved
Part of https://github.com/opensearch-project/documentation-website/issues/1483 addressed in this PR.

### Version
All

### Frontend features
n/a

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-09-30 17:50 UTC, vagimeli commented
@udabhas Will you review this PR for technical accuracy, or have a peer review it? Thank you.

2024-12-09 11:42 UTC, udabhas approved these changes
Looks good to me.

2025-01-03 11:35 UTC, natebower requested changes
@kolchfa-aws Please see my comments and changes and tag me for approval when complete. Thanks!

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +The `edge_ngram` tokenizer generates partial word tokens, or n-grams, starting from the beginning of each word. It splits the text based on specified characters and produces tokens with lengths defin
```suggestion
The `edge_ngram` tokenizer generates partial word tokens, or _n-grams_, starting from the beginning of each word. It splits the text based on specified characters and produces tokens within a defined minimum and maximum length range. This tokenizer is particularly useful for implementing search-as-you-type functionality. 
```

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +
Line 10: If my rewrite to the second sentence isn't quite right, then let's name what we're referring to: "produces tokens of lengths defined by `min_gram` and `max_gram`."

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +Edge n-grams are ideal for autocomplete searches where the order of the words may vary, such as with product names or addresses. For more information, see [Autocomplete]({{site.url}}{{site.baseurl}}/
```suggestion
Edge n-grams are ideal for autocomplete searches where the order of the words may vary, such as when searching for product names or addresses. For more information, see [Autocomplete]({{site.url}}{{site.baseurl}}/search-plugins/searching-data/autocomplete/). However, for text with a fixed order, like movie or song titles, the completion suggester may be more efficient.
```

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +
Line 12: "efficient" => "accurate"?

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +By default, the `edge n-gram` tokenizer produces tokens with a minimum length of `1` and a maximum length of `2`. For example, analyzing the text `OpenSearch` with the default configuration will prod
```suggestion
By default, the `edge n-gram` tokenizer produces tokens with a minimum length of `1` and a maximum length of `2`. For example, when analyzing the text `OpenSearch`, the default configuration will produce the `O` and `Op` n-grams. These short n-grams are often not sufficient for meaningful searches, so configuring the tokenizer is necessary in order to adjust the n-gram lengths.
```

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +
Line 14: "not sufficient for meaningful searches" is a bit too ambiguous/imprecise. Please clarify/simplify.

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +The following example request creates a new index named `my_index` and configures an analyzer with a `edge_ngram` tokenizer. The tokenizer produces tokens 3--6 characters in length, considering both
```suggestion
The following example request creates a new index named `my_index` and configures an analyzer with an `edge_ngram` tokenizer. The tokenizer produces tokens 3--6 characters in length, considering both letters and symbols to be valid token characters:
```

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +| Parameter           | Required/Optional | Data Type        | Description    |
```suggestion
| Parameter           | Required/Optional | Data type        | Description    |
```

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +| `token_chars`       | Optional          | Array of strings | Defines character classes to include in tokens. Tokens are split on characters not in these classes. Default includes all characters. Av
```suggestion
| `token_chars`       | Optional          | Array of strings | Defines character classes to include in tokens. Tokens are split on characters not included in these classes. Default includes all characters. Available classes include: <br> - `letter`: Alphabetic characters (for example, `a`, `ç`, or `京`) <br> - `digit`: Numeric characters (for example, `3` or `7`) <br>- `punctuation`: Punctuation symbols (for example, `!` or `?`) <br> - `symbol`: Other symbols (for example, `$` or `√`) <br> - `whitespace`: Space or newline characters <br> - `custom`: Allows you to specify custom characters in the `custom_token_chars` setting. |
```

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +
Line 109: split "on" or "at"?

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +## The max_gram parameter limitations
```suggestion
## max_gram parameter limitations
```

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +For instance, if `max_gram` is set to `4`, the query `explore` would be tokenized as `expl` during indexing. As a result, a search for the full term `explore` will not match the indexed token `expl`.
```suggestion
For example, if `max_gram` is set to `4`, the query `explore` would be tokenized as `expl` during indexing. As a result, a search for the full term `explore` will not match the indexed token `expl`.
```

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +To address this limitation, you can apply a `truncate` token filter to shorten search terms to the maximum token length. However, this approach has trade-offs. Truncating `explore` to `expl` might le
```suggestion
To address this limitation, you can apply a `truncate` token filter to shorten search terms to the maximum token length. However, this approach presents trade-offs. Truncating `explore` to `expl` might lead to matches with unrelated terms like `explosion` or `explicit`, reducing search precision.
```

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +We recommend using the `edge_ngram` tokenizer only at indexing time to ensure partial word tokens are stored. At search time, a simpler analyzer should be used to match full user queries.
```suggestion
We recommend using the `edge_ngram` tokenizer only at indexing time in order to ensure that partial word tokens are stored. At search time, a simpler analyzer should be used to match full user queries.
```

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +
Line 124: The last sentence is a bit too vague. Can we be more precise than "a simpler analyzer" (this is presumably somewhat subjective)? What precisely do we mean by "full user queries"?

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +##  Configuring search as you type
```suggestion
## Configuring search-as-you-type functionality
```

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +To implement search-as-you-type functionality, use the `edge_ngram` tokenizer during indexing and a simpler analyzer at search time. The following configuration demonstrates this approach:
Same comment re: "a simpler analyzer". What/which ones would constitute "a simpler analyzer"?

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +Index a document containing a `product` field and refresh the index:
This line reads as though we're providing instructions, but line 128 implies merely a demonstration.

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +This configuration ensures that the `edge_ngram` tokenizer breaks terms like Laptop into tokens such as `La`, `Lap`, and `Lapt`, allowing partial matches during search. At search time, the standard t
```suggestion
This configuration ensures that the `edge_ngram` tokenizer breaks terms like "Laptop" into tokens such as `La`, `Lap`, and `Lapt`, allowing partial matches during search. At search time, the standard tokenizer simplifies queries while ensuring that matches are case-insensitive because of the lowercase filter.
```

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +
Is "the standard tokenizer" what we mean by "a simpler analyzer" on lines 124 and 128?

2025-01-03 11:35 UTC, natebower commented on _analyzers/tokenizers/edge-n-gram.md
> +Now, searches for `laptop Pr` or `lap pr` retrieve the relevant document based on partial matches:
```suggestion
Searches for `laptop Pr` or `lap pr` now retrieve the relevant document based on partial matches:
```

2025-01-03 14:19 UTC, kolchfa-aws commented on _analyzers/tokenizers/edge-n-gram.md
> +
I always go with "on".

2025-01-03 14:56 UTC, kolchfa-aws commented on _analyzers/tokenizers/edge-n-gram.md
> +
reworded.

2025-01-03 14:58 UTC, kolchfa-aws commented on _analyzers/tokenizers/edge-n-gram.md
> +To implement search-as-you-type functionality, use the `edge_ngram` tokenizer during indexing and a simpler analyzer at search time. The following configuration demonstrates this approach:
```suggestion
To implement search-as-you-type functionality, use the `edge_ngram` tokenizer during indexing and an analyzer that performs minimal processing at search time. The following example demonstrates this approach.

Create an index with an `edge_ngram` tokenizer:
```

2025-01-03 14:58 UTC, kolchfa-aws commented on _analyzers/tokenizers/edge-n-gram.md
> +Index a document containing a `product` field and refresh the index:
Reworded the previous line as instructions

2025-01-03 14:59 UTC, kolchfa-aws commented on _analyzers/tokenizers/edge-n-gram.md
> +
No, the `standard` tokenizer.

2025-01-03 15:01 UTC, natebower approved these changes
@kolchfa-aws LGTM!

2025-01-03 16:53 UTC, merged