Add custom parameters page
opensearch-project/documentation-website pull request #8495
Opened 2024-10-10 18:24 UTC by Naarcha-AWS

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-20 17:06 UTC, gkamat reviewed
The sections for Parameter Sources and Custom Runners should be completely separate, since they pertain to entirely different items.  Also, the examples should be re-written, to make them easier to understand.

We can provide new examples, but for now, the existing text should suffice.  Separating the sections can perhaps be done as part of the current PR.

2024-10-24 19:14 UTC, Naarcha-AWS commented
@gkamat: I separated both files. Let me know what additional modifications you would like me to make.

2024-10-25 20:35 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/custom-runners.md
> +**Runners** are operation types performed on an OpenSearch cluster.
For adding support for an operation that doesn't exist in OSB already.

```suggestion
**Runners** are operation types performed on an OpenSearch cluster. 
```

2024-10-25 20:39 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/custom-parameter-sources.md
> +A **parameter source** is a source outside of OpenSearch Benchmark that provides parameters to an operation.
```suggestion
A **parameter source** is a source outside of OpenSearch Benchmark that provides parameters to an operation. You can add parameters to an existing operation in OpenSearch Benchmark or add custom parameters to a [runner]({{site.url}}{{site.baseurl}}/benchmark/user-guide/optimizing-benchmarks/custom-runners/).
```

2024-11-04 05:23 UTC, gkamat approved these changes
Will provide better examples of both items shortly.

2024-11-05 18:58 UTC, IanHoang requested changes
Let's test this out before we merge this, as there might be some bugs.

2024-11-05 18:58 UTC, IanHoang commented on _benchmark/user-guide/optimizing-benchmarks/custom-runners.md
> +**Runners** are operation types performed on an OpenSearch cluster. You can add customer runners for operations that don't already exist in a workload.
> for operation types that do not exist in OpenSearch Benchmark (OSB).
Could we also link the types of operations that exist in OSB from the documentation?

2024-11-05 18:58 UTC, IanHoang commented on _benchmark/user-guide/optimizing-benchmarks/custom-parameter-sources.md
> +    def random_profession(workload, params, **movies):
random_profession -> random_pixar_movie

2024-11-05 18:58 UTC, IanHoang commented on _benchmark/user-guide/optimizing-benchmarks/custom-parameter-sources.md
> +2. In both fields, add a `param-source` field to the operation, specifying the name of the parameter source. Add any additional fields which contain your custom parameters. For example, if you want t
professions -> movies

2024-11-05 18:58 UTC, IanHoang commented on _benchmark/user-guide/optimizing-benchmarks/custom-parameter-sources.md
> +2. In both fields, add a `param-source` field to the operation, specifying the name of the parameter source. Add any additional fields which contain your custom parameters. For example, if you want t
["Inside Out", "The Incredibles", "Ratatouille"]

2024-11-05 18:58 UTC, IanHoang commented on _benchmark/user-guide/optimizing-benchmarks/custom-parameter-sources.md
> +        "professions": ["mechanic", "physician", "nurse"]
"movies": ["Inside Out", "The Incredibles", "Ratatouille"]

2024-11-05 18:58 UTC, IanHoang commented on _benchmark/user-guide/optimizing-benchmarks/custom-parameter-sources.md
> +3. In `workload.py` add the method or function for your custom parameter sources. The runner expects the parameter sources provided in step 2. The following example makes the workload use the `random
random_profession() -> random_pixar_movie()

2024-11-05 18:58 UTC, IanHoang commented on _benchmark/user-guide/optimizing-benchmarks/custom-parameter-sources.md
> +        registry.register_param_source("my-custom-term-param-source", random_movie)
random_pixar_movie

2024-11-05 18:58 UTC, IanHoang commented on _benchmark/user-guide/optimizing-benchmarks/custom-parameter-sources.md
> +        "param-source": "my-custom-term-param-source"
my-custom-term-param-source be renamed to custom-pixar-movies

2024-11-05 18:58 UTC, IanHoang commented on _benchmark/user-guide/optimizing-benchmarks/custom-parameter-sources.md
> +3. In `workload.py` add the method or function for your custom parameter sources. The runner expects the parameter sources provided in step 2. The following example makes the workload use the `random
my-custom-term-param-source be renamed to custom-pixar-movies

2024-11-05 18:58 UTC, IanHoang commented on _benchmark/user-guide/optimizing-benchmarks/custom-parameter-sources.md
> +        registry.register_param_source("my-custom-term-param-source", random_movie)
my-custom-term-param-source be renamed to custom-pixar-movies

2024-11-05 18:58 UTC, IanHoang commented on _benchmark/user-guide/optimizing-benchmarks/custom-parameter-sources.md
> +            registry.register_param_source("my-custom-term-param-source", TermParamSource)
my-custom-term-param-source be renamed to custom-pixar-movies

2024-11-05 18:58 UTC, IanHoang commented on _benchmark/user-guide/optimizing-benchmarks/custom-parameter-sources.md
> +                        "body": "%s" % random.choice(params["movies"])
movies -> kwargs

2024-11-05 18:58 UTC, IanHoang commented on _benchmark/user-guide/optimizing-benchmarks/custom-parameter-sources.md
> +        def __init__(self, workload, params, **movies):
movies --> kwargs

2024-12-05 21:31 UTC, closed without merging