Configuration changes to lambda processor and sink
opensearch-project/documentation-website pull request #8781
Opened 2024-11-19 17:25 UTC by srikanthjg

### Description
Configuration changes to lambda processor and sink

### Issues Resolved
Addresses #8655 

### Version
_List the OpenSearch version to which this PR applies, e.g. 2.14, 2.12--2.14, or all._

### Frontend features
_If you're submitting documentation for an OpenSearch Dashboards feature, add a video that shows how a user will interact with the UI step by step. A voiceover is optional._ 

### Checklist
- [ ] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-11-22 21:01 UTC, vagimeli commented
@srikanthjg We already have existing documentation on these topics. Of concern is the sink file. Please update the existing file instead of creating a new file. The published document is available at https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sinks/aws-lambda/. The file in the documentation-website repo is  aws-lambda.md

2024-11-22 21:02 UTC, vagimeli requested changes
The existing files should be updated. This content already exists and is published.

2024-11-22 21:05 UTC, vagimeli commented on _data-prepper/pipelines/configuration/processors/aws-lambda.md
> +| `response_events_match` | Boolean  | Optional | `false` | The Lambda response handling behavio                                           |
```suggestion
| `response_events_match` | Boolean  | Optional | `false` | The Lambda response handling behavior                                           |
```

2025-07-08 11:22 UTC, Naarcha-AWS commented
Closing this for now. Feel free to reopen if the changes are still relevant.

2025-07-08 11:22 UTC, closed without merging