Add documentation for OSB query randomization
opensearch-project/documentation-website pull request #8990
Opened 2024-12-27 22:58 UTC by peteralfonsi

### Description
Adds a documentation page describing what OSB query randomization is and how to use it. As @IanHoang suggested in https://github.com/opensearch-project/opensearch-benchmark/pull/712 I've put this under the Optimizing Benchmarks section. 

### Issues Resolved
Closes https://github.com/opensearch-project/documentation-website/issues/8989

### Version
The whole page describes how the feature will work once the pending https://github.com/opensearch-project/opensearch-benchmark/pull/712 goes in, which will likely go into OSB 1.12. Most of the feature is present in OSB 1.3 and one flag was added in OSB 1.8. I can split up this PR into separate chunks to be backported separately if that's the right way to do things. 

### Frontend features
N/A

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-12-31 17:10 UTC, peteralfonsi commented
Addressed most of the style guide complaints, but it seems to be upset by the proper noun "Zipf" as in "Zipf distribution".

2025-01-02 18:42 UTC, Naarcha-AWS commented
Adding a blocked label to this for now until the development PR is merged. I'll go ahead and edit the content in the meantime.

2025-01-07 19:21 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +Every time a query is sent to OpenSearch, some fraction `rf` (short for "repeat-frequency") of the time, we draw a pair from this saved list. This pair may have been seen before, so it could cause a
By `pair` do we mean "value pairs"?

2025-01-07 19:41 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +#### Randomizing non-range queries
@peteralfonsi: Does this section only pertain to modifying `workload.py`?

2025-01-07 19:52 UTC, Naarcha-AWS commented
@peteralfonsi and @IanHoang: I added my edits on top of this. Can one or both of y'all take a look and make sure my adjustments are still technically accurate?

2025-01-07 20:37 UTC, peteralfonsi commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +#### Randomizing non-range queries
Yes. To randomize non-range queries you have to do this additional step, which is only within `workload.py`. No additional flags or anything are required.

2025-01-07 20:39 UTC, peteralfonsi commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +The third argument is a list of lists: `[["top_left"], ["bottom_right"]]`. Each entry in the outer list represents one parameter name that will be randomized. It's a list because we may have multiple
We should have 4 arguments - `"bbox"`, `"geo_bounding_box"`, `[["top_left"], ["bottom_right"]]`, and `[]`. May have missed the description of the second argument `"geo_bounding_box"` as it's in the same paragraph as the description of the first argument?

2025-01-07 20:46 UTC, peteralfonsi commented
Looks good to me. I tweaked the new language in the Overview section slightly, to make it clearer why we need to reuse values, and also to make it clearer that the generation of saved value pairs is something that OSB does itself, rather than something the user has to do.

2025-01-08 13:46 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +## Overview
```suggestion

```

2025-01-08 13:47 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +Specify how to generate the saved value pairs for each operation by registering a “standard value source” for that operation. This Python function accepts no arguments and returns a dictionary. The k
```suggestion
Specify how to generate the saved value pairs for each operation by registering a “standard value source” for that operation. This Python function accepts no arguments and returns a dictionary. The keys mirror those in the input query, but are randomized. Finally, change the `register()` method to register this function with the operation name and field name, which is randomized.
```

2025-01-09 11:58 UTC, natebower requested changes
@Naarcha-AWS @peteralfonsi Please see my comments and changes and tag me for approval when complete. Thanks!

2025-01-09 11:58 UTC, natebower commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +
Line 37: In the second sentence, the second phrase doesn't appear to logically follow the first. Do we mean something like "`alpha` represents a parameter that controls the spread of the distribution"? In the last sentence, what is meant by "low indexes" and "high indexes"? Please clarify.

2025-01-09 11:58 UTC, natebower commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +- `--randomization-enabled` turns randomization on and off. If randomization is not enabled, none of the randomization flags will have an effect.
"will have an effect" => "will be applied"?

2025-01-09 11:58 UTC, natebower commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +- `--randomization-repeat-frequency` or `-rf` sets the fraction of pairs drawn from the saved value pairs generated at the start of the benchmark. The value should be between `0.0` and `1.0`.  Defaul
```suggestion
- `--randomization-repeat-frequency` or `-rf` sets the fraction of pairs drawn from the saved value pairs generated at the start of the benchmark. The value should be between `0.0` and `1.0`. Default is `0.3`. 
```

2025-01-09 11:58 UTC, natebower commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +- `--randomization-alpha` sets the parameter `alpha` controlling the shape of the `Zipf` distribution. The value should be `>=0`. Lower values spread out the distribution more. Default is `1.0`.
```suggestion
- `--randomization-alpha` sets the `alpha` parameter, which controls the spread of the `Zipf` distribution. The value should be `>=0`. Lower values increase the spread of the distribution. Default is `1.0`. 
```

2025-01-09 16:32 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +- `--randomization-enabled` turns randomization on and off. If randomization is not enabled, none of the randomization flags will have an effect.
```suggestion
- `--randomization-enabled` turns randomization on and off. If randomization is not enabled, none of the randomization flags will be applied.
```

2025-01-09 16:37 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +
This is an explanation of the [`Zipf` law of distribution](https://www.w3schools.com/python/numpy/numpy_random_zipf.asp). In our case, `i^alpha` would represent the `nth` common term. The sentence, as written, assumes previous knowledge of the `Zipf` law, however, @peteralfonsi, should we go a little deeper on this explanation?

2025-01-09 16:38 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +Saved value pairs are based on the `Zipf` distribution, which empirically matches usage traces for many real caches. For example, if the benchmark draws pair `i` with a probability proportional to `1
```suggestion
Saved value pairs are based on the `Zipf` distribution, which empirically matches term usage for many real caches. For example, if the benchmark draws pair `i` with a probability proportional to `1 / i^alpha`, `alpha` would represent another parameter controlling the spread of the distribution. Pairs with low indexes appear with a much higher frequency than those with high indexes.
```

2025-01-09 16:39 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +
Also, @peteralfonsi, by "high indexes" and "low indexes", do we mean the order appear in the saved list relative to their terms?

2025-01-09 16:41 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +You can't completely randomize the values because the cache would not get any hits. To get cache hits, the cache must sometimes see the same values. To account for the same values while randomizing,
```suggestion
You can't completely randomize the values because the cache would not get any hits. To get cache hits, the cache must sometimes encounter the same values. To account for the same values while randomizing, OpenSearch Benchmark generates a number `N` of value pairs for each randomized operation at the beginning of the benchmark. OpenSearch Benchmark stores these values in a saved list where each pair is assigned an index from `1` to `N`.
```

2025-01-09 16:41 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +
@natebower: Does the above suggestion work?

2025-01-09 17:19 UTC, natebower commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +If there is no registration, the default registration is used, `registry.register_query_randomization_info(<operation_name>, “range”, [[“gte”, “gt”], [“lte”, “lt”]], [“format”])`.
```suggestion
If there is no registration, the default registration is used: `registry.register_query_randomization_info(<operation_name>, “range”, [[“gte”, “gt”], [“lte”, “lt”]], [“format”])`.
```

2025-01-09 18:54 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +
@natebower: Suggestion updated with additional details from @peteralfonsi. The `$` should appear as an equation in the final published page. I'll verify this before merging.

2025-01-09 19:04 UTC, natebower commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +
@Naarcha-AWS I edited the first four sentences, but I'm still not following the last one. Is there extra text?

2025-01-09 19:37 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +
@natebower: How does this sound? 

"Therefore, pairs with numerically lower indexes, or indexes closer to `1` in the saved list, appear with a higher frequency in the cache. Consequently, versus pairs with numerically higher indexes, or indexes closer to `N` on the saved list, appear with a lower frequency."

2025-01-09 19:42 UTC, natebower commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +
I feel like there's some context missing here that's making the paragraph difficult to parse/comprehend. @kolchfa-aws Would you mind helping out with this one?

2025-01-09 20:02 UTC, kolchfa-aws commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +
How about (this needs to be formatted for math though):

OpenSearch Benchmark selects saved value pairs using the Zipf probability distribution, where the probability of selecting pair i is proportional to 1/i^α. In this formula, i represents the index of the saved value pair, and α controls how concentrated the distribution is. This distribution reflects usage patterns observed in real caches. Pairs with lower i values (closer to 1) are selected more frequently, while pairs with higher i values (closer to N) are selected less often.

2025-01-09 20:04 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +
Works for me if it works for @peteralfonsi.

2025-01-09 20:05 UTC, natebower commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +
@kolchfa-aws @Naarcha-AWS LGTM. Let's go with this. Thanks!

2025-01-09 20:06 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +
Wait... I'm not sure `i` represents the numerical index value. I thought that `i` represents the term value.

2025-01-09 20:59 UTC, Naarcha-AWS commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +
> Wait... I'm not sure `i` represents the numerical index value. I thought that `i` represents the term value.

Getting clarification on this before adjusting the suggestion. Thanks for your help @kolchfa-aws and @natebower!

2025-01-09 21:03 UTC, Naarcha-AWS commented
@natebower: Fanit's suggestion implemented, waiting for your approval.

2025-01-09 21:09 UTC, natebower commented on _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
> +OpenSearch Benchmark selects saved value pairs using the Zipf probability distribution, where the probability of selecting pair `i` is proportional to `1/i^α`. In this formula, i represents the index
```suggestion
OpenSearch Benchmark selects saved value pairs using the Zipf probability distribution, where the probability of selecting pair `i` is proportional to `1/i^α`. In this formula, `i` represents the index of the saved value pair, and `α` controls how concentrated the distribution is. This distribution reflects usage patterns observed in real caches. Pairs with lower `i` values (closer to `1`) are selected more frequently, while pairs with higher `i` values (closer to `N`) are selected less often.
```

2025-01-09 21:27 UTC, natebower approved these changes
@Naarcha-AWS LGTM

2025-01-09 22:07 UTC, merged